#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "UAV_with_prop_observ_alloc.h"

/* C code generated by lustrec
   Version number 1.7
   Code is C99 compliant
   Using (double) floating-point numbers */
   
void usage(char *argv[]) {
  printf("Usage: %s\n", argv[0]);
  printf(" -t: produce trace files for input/output flows\n");
  printf(" -d<dir>: directory containing traces (default: _traces)\n");
  printf(" -p<prefix>: prefix_simu.scope<id> (default: file_node)\n");
  exit (8);
  }
int main (int argc, char *argv[]) {
  int traces = 0;
  char* prefix = "UAV_with_prop_observ_quadcopter_model_Lustre_STL_PP";
  char* dir = ".";
  while ((argc > 1) && (argv[1][0] == '-')) {
    switch (argv[1][1]) {
      case 't':
        traces = 1;
        break;
        
      case 'd':
        dir = &argv[1][2];
        break;
        
      case 'p':
        prefix = &argv[1][2];
        break;
        
      default:
        printf("Wrong Argument: %s\n", argv[1]);
        usage(argv);
        
      }
    ++argv;
    --argc;
    }
  /* Declaration of inputs/outputs variables */
  double input_att;
  FILE *f_in1;
  double input_alt;
  FILE *f_in2;
  double ov_spec_bound;
  FILE *f_in3;
  double rt_spec_bound;
  FILE *f_in4;
  double st_spec_bound;
  FILE *f_in5;
  double ss_spec_bound;
  FILE *f_in6;
  double APE_spec_bound;
  FILE *f_in7;
  double MPE_spec_bound;
  FILE *f_in8;
  double RPE_spec_bound;
  FILE *f_in9;
  double PDE_spec_bound;
  FILE *f_in10;
  _Bool trigger_ESA_att;
  FILE *f_in11;
  int rt_spec_time;
  FILE *f_in12;
  int st_spec_time;
  FILE *f_in13;
  int inv_Ts;
  FILE *f_in14;
  int b;
  FILE *f_in15;
  double __time_step;
  FILE *f_out1;
  _Bool eval_ov_att;
  FILE *f_out2;
  _Bool trigger_ov_att;
  FILE *f_out3;
  _Bool eval_rt_att;
  FILE *f_out4;
  _Bool trigger_rt_att;
  FILE *f_out5;
  _Bool eval_st_att;
  FILE *f_out6;
  _Bool trigger_st_att;
  FILE *f_out7;
  _Bool eval_ss_att;
  FILE *f_out8;
  _Bool trigger_ss_att;
  FILE *f_out9;
  _Bool eval_APE_att;
  FILE *f_out10;
  _Bool eval_MPE_att;
  FILE *f_out11;
  _Bool eval_RPE_att;
  FILE *f_out12;
  _Bool eval_PDE_att;
  FILE *f_out13;
  double Attitudecontrol_1;
  FILE *f_out14;
  if (traces) {
    const char* cst_char_suffix_in1 = "_simu.in1";
    size_t lin1 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in1);
    char* f_in1_name = malloc((lin1+2) * sizeof(char));
    strcpy (f_in1_name, dir);
    strcat(f_in1_name, "/");
    strcat(f_in1_name, prefix);
    strcat(f_in1_name, cst_char_suffix_in1);
    f_in1 = fopen(f_in1_name, "w");
    free(f_in1_name);
    const char* cst_char_suffix_in2 = "_simu.in2";
    size_t lin2 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in2);
    char* f_in2_name = malloc((lin2+2) * sizeof(char));
    strcpy (f_in2_name, dir);
    strcat(f_in2_name, "/");
    strcat(f_in2_name, prefix);
    strcat(f_in2_name, cst_char_suffix_in2);
    f_in2 = fopen(f_in2_name, "w");
    free(f_in2_name);
    const char* cst_char_suffix_in3 = "_simu.in3";
    size_t lin3 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in3);
    char* f_in3_name = malloc((lin3+2) * sizeof(char));
    strcpy (f_in3_name, dir);
    strcat(f_in3_name, "/");
    strcat(f_in3_name, prefix);
    strcat(f_in3_name, cst_char_suffix_in3);
    f_in3 = fopen(f_in3_name, "w");
    free(f_in3_name);
    const char* cst_char_suffix_in4 = "_simu.in4";
    size_t lin4 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in4);
    char* f_in4_name = malloc((lin4+2) * sizeof(char));
    strcpy (f_in4_name, dir);
    strcat(f_in4_name, "/");
    strcat(f_in4_name, prefix);
    strcat(f_in4_name, cst_char_suffix_in4);
    f_in4 = fopen(f_in4_name, "w");
    free(f_in4_name);
    const char* cst_char_suffix_in5 = "_simu.in5";
    size_t lin5 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in5);
    char* f_in5_name = malloc((lin5+2) * sizeof(char));
    strcpy (f_in5_name, dir);
    strcat(f_in5_name, "/");
    strcat(f_in5_name, prefix);
    strcat(f_in5_name, cst_char_suffix_in5);
    f_in5 = fopen(f_in5_name, "w");
    free(f_in5_name);
    const char* cst_char_suffix_in6 = "_simu.in6";
    size_t lin6 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in6);
    char* f_in6_name = malloc((lin6+2) * sizeof(char));
    strcpy (f_in6_name, dir);
    strcat(f_in6_name, "/");
    strcat(f_in6_name, prefix);
    strcat(f_in6_name, cst_char_suffix_in6);
    f_in6 = fopen(f_in6_name, "w");
    free(f_in6_name);
    const char* cst_char_suffix_in7 = "_simu.in7";
    size_t lin7 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in7);
    char* f_in7_name = malloc((lin7+2) * sizeof(char));
    strcpy (f_in7_name, dir);
    strcat(f_in7_name, "/");
    strcat(f_in7_name, prefix);
    strcat(f_in7_name, cst_char_suffix_in7);
    f_in7 = fopen(f_in7_name, "w");
    free(f_in7_name);
    const char* cst_char_suffix_in8 = "_simu.in8";
    size_t lin8 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in8);
    char* f_in8_name = malloc((lin8+2) * sizeof(char));
    strcpy (f_in8_name, dir);
    strcat(f_in8_name, "/");
    strcat(f_in8_name, prefix);
    strcat(f_in8_name, cst_char_suffix_in8);
    f_in8 = fopen(f_in8_name, "w");
    free(f_in8_name);
    const char* cst_char_suffix_in9 = "_simu.in9";
    size_t lin9 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in9);
    char* f_in9_name = malloc((lin9+2) * sizeof(char));
    strcpy (f_in9_name, dir);
    strcat(f_in9_name, "/");
    strcat(f_in9_name, prefix);
    strcat(f_in9_name, cst_char_suffix_in9);
    f_in9 = fopen(f_in9_name, "w");
    free(f_in9_name);
    const char* cst_char_suffix_in10 = "_simu.in10";
    size_t lin10 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in10);
    char* f_in10_name = malloc((lin10+2) * sizeof(char));
    strcpy (f_in10_name, dir);
    strcat(f_in10_name, "/");
    strcat(f_in10_name, prefix);
    strcat(f_in10_name, cst_char_suffix_in10);
    f_in10 = fopen(f_in10_name, "w");
    free(f_in10_name);
    const char* cst_char_suffix_in11 = "_simu.in11";
    size_t lin11 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in11);
    char* f_in11_name = malloc((lin11+2) * sizeof(char));
    strcpy (f_in11_name, dir);
    strcat(f_in11_name, "/");
    strcat(f_in11_name, prefix);
    strcat(f_in11_name, cst_char_suffix_in11);
    f_in11 = fopen(f_in11_name, "w");
    free(f_in11_name);
    const char* cst_char_suffix_in12 = "_simu.in12";
    size_t lin12 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in12);
    char* f_in12_name = malloc((lin12+2) * sizeof(char));
    strcpy (f_in12_name, dir);
    strcat(f_in12_name, "/");
    strcat(f_in12_name, prefix);
    strcat(f_in12_name, cst_char_suffix_in12);
    f_in12 = fopen(f_in12_name, "w");
    free(f_in12_name);
    const char* cst_char_suffix_in13 = "_simu.in13";
    size_t lin13 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in13);
    char* f_in13_name = malloc((lin13+2) * sizeof(char));
    strcpy (f_in13_name, dir);
    strcat(f_in13_name, "/");
    strcat(f_in13_name, prefix);
    strcat(f_in13_name, cst_char_suffix_in13);
    f_in13 = fopen(f_in13_name, "w");
    free(f_in13_name);
    const char* cst_char_suffix_in14 = "_simu.in14";
    size_t lin14 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in14);
    char* f_in14_name = malloc((lin14+2) * sizeof(char));
    strcpy (f_in14_name, dir);
    strcat(f_in14_name, "/");
    strcat(f_in14_name, prefix);
    strcat(f_in14_name, cst_char_suffix_in14);
    f_in14 = fopen(f_in14_name, "w");
    free(f_in14_name);
    const char* cst_char_suffix_in15 = "_simu.in15";
    size_t lin15 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_in15);
    char* f_in15_name = malloc((lin15+2) * sizeof(char));
    strcpy (f_in15_name, dir);
    strcat(f_in15_name, "/");
    strcat(f_in15_name, prefix);
    strcat(f_in15_name, cst_char_suffix_in15);
    f_in15 = fopen(f_in15_name, "w");
    free(f_in15_name);
    const char* cst_char_suffix_out1 = "_simu.out1";
    size_t lout1 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out1);
    char* f_out1_name = malloc((lout1+2) * sizeof(char));
    strcpy (f_out1_name, dir);
    strcat(f_out1_name, "/");
    strcat(f_out1_name, prefix);
    strcat(f_out1_name, cst_char_suffix_out1);
    f_out1 = fopen(f_out1_name, "w");
    free(f_out1_name);
    const char* cst_char_suffix_out2 = "_simu.out2";
    size_t lout2 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out2);
    char* f_out2_name = malloc((lout2+2) * sizeof(char));
    strcpy (f_out2_name, dir);
    strcat(f_out2_name, "/");
    strcat(f_out2_name, prefix);
    strcat(f_out2_name, cst_char_suffix_out2);
    f_out2 = fopen(f_out2_name, "w");
    free(f_out2_name);
    const char* cst_char_suffix_out3 = "_simu.out3";
    size_t lout3 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out3);
    char* f_out3_name = malloc((lout3+2) * sizeof(char));
    strcpy (f_out3_name, dir);
    strcat(f_out3_name, "/");
    strcat(f_out3_name, prefix);
    strcat(f_out3_name, cst_char_suffix_out3);
    f_out3 = fopen(f_out3_name, "w");
    free(f_out3_name);
    const char* cst_char_suffix_out4 = "_simu.out4";
    size_t lout4 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out4);
    char* f_out4_name = malloc((lout4+2) * sizeof(char));
    strcpy (f_out4_name, dir);
    strcat(f_out4_name, "/");
    strcat(f_out4_name, prefix);
    strcat(f_out4_name, cst_char_suffix_out4);
    f_out4 = fopen(f_out4_name, "w");
    free(f_out4_name);
    const char* cst_char_suffix_out5 = "_simu.out5";
    size_t lout5 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out5);
    char* f_out5_name = malloc((lout5+2) * sizeof(char));
    strcpy (f_out5_name, dir);
    strcat(f_out5_name, "/");
    strcat(f_out5_name, prefix);
    strcat(f_out5_name, cst_char_suffix_out5);
    f_out5 = fopen(f_out5_name, "w");
    free(f_out5_name);
    const char* cst_char_suffix_out6 = "_simu.out6";
    size_t lout6 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out6);
    char* f_out6_name = malloc((lout6+2) * sizeof(char));
    strcpy (f_out6_name, dir);
    strcat(f_out6_name, "/");
    strcat(f_out6_name, prefix);
    strcat(f_out6_name, cst_char_suffix_out6);
    f_out6 = fopen(f_out6_name, "w");
    free(f_out6_name);
    const char* cst_char_suffix_out7 = "_simu.out7";
    size_t lout7 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out7);
    char* f_out7_name = malloc((lout7+2) * sizeof(char));
    strcpy (f_out7_name, dir);
    strcat(f_out7_name, "/");
    strcat(f_out7_name, prefix);
    strcat(f_out7_name, cst_char_suffix_out7);
    f_out7 = fopen(f_out7_name, "w");
    free(f_out7_name);
    const char* cst_char_suffix_out8 = "_simu.out8";
    size_t lout8 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out8);
    char* f_out8_name = malloc((lout8+2) * sizeof(char));
    strcpy (f_out8_name, dir);
    strcat(f_out8_name, "/");
    strcat(f_out8_name, prefix);
    strcat(f_out8_name, cst_char_suffix_out8);
    f_out8 = fopen(f_out8_name, "w");
    free(f_out8_name);
    const char* cst_char_suffix_out9 = "_simu.out9";
    size_t lout9 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out9);
    char* f_out9_name = malloc((lout9+2) * sizeof(char));
    strcpy (f_out9_name, dir);
    strcat(f_out9_name, "/");
    strcat(f_out9_name, prefix);
    strcat(f_out9_name, cst_char_suffix_out9);
    f_out9 = fopen(f_out9_name, "w");
    free(f_out9_name);
    const char* cst_char_suffix_out10 = "_simu.out10";
    size_t lout10 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out10);
    char* f_out10_name = malloc((lout10+2) * sizeof(char));
    strcpy (f_out10_name, dir);
    strcat(f_out10_name, "/");
    strcat(f_out10_name, prefix);
    strcat(f_out10_name, cst_char_suffix_out10);
    f_out10 = fopen(f_out10_name, "w");
    free(f_out10_name);
    const char* cst_char_suffix_out11 = "_simu.out11";
    size_t lout11 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out11);
    char* f_out11_name = malloc((lout11+2) * sizeof(char));
    strcpy (f_out11_name, dir);
    strcat(f_out11_name, "/");
    strcat(f_out11_name, prefix);
    strcat(f_out11_name, cst_char_suffix_out11);
    f_out11 = fopen(f_out11_name, "w");
    free(f_out11_name);
    const char* cst_char_suffix_out12 = "_simu.out12";
    size_t lout12 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out12);
    char* f_out12_name = malloc((lout12+2) * sizeof(char));
    strcpy (f_out12_name, dir);
    strcat(f_out12_name, "/");
    strcat(f_out12_name, prefix);
    strcat(f_out12_name, cst_char_suffix_out12);
    f_out12 = fopen(f_out12_name, "w");
    free(f_out12_name);
    const char* cst_char_suffix_out13 = "_simu.out13";
    size_t lout13 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out13);
    char* f_out13_name = malloc((lout13+2) * sizeof(char));
    strcpy (f_out13_name, dir);
    strcat(f_out13_name, "/");
    strcat(f_out13_name, prefix);
    strcat(f_out13_name, cst_char_suffix_out13);
    f_out13 = fopen(f_out13_name, "w");
    free(f_out13_name);
    const char* cst_char_suffix_out14 = "_simu.out14";
    size_t lout14 = strlen(dir) + strlen(prefix) + strlen(cst_char_suffix_out14);
    char* f_out14_name = malloc((lout14+2) * sizeof(char));
    strcpy (f_out14_name, dir);
    strcat(f_out14_name, "/");
    strcat(f_out14_name, prefix);
    strcat(f_out14_name, cst_char_suffix_out14);
    f_out14 = fopen(f_out14_name, "w");
    free(f_out14_name);
    }
  
  if (traces) {
    }
  
  /* Main memory allocation */
  quadcopter_model_Lustre_STL_PP_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  quadcopter_model_Lustre_STL_PP_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    if (traces) {
      fflush(f_in1);
      fflush(f_in2);
      fflush(f_in3);
      fflush(f_in4);
      fflush(f_in5);
      fflush(f_in6);
      fflush(f_in7);
      fflush(f_in8);
      fflush(f_in9);
      fflush(f_in10);
      fflush(f_in11);
      fflush(f_in12);
      fflush(f_in13);
      fflush(f_in14);
      fflush(f_in15);
      fflush(f_out1);
      fflush(f_out2);
      fflush(f_out3);
      fflush(f_out4);
      fflush(f_out5);
      fflush(f_out6);
      fflush(f_out7);
      fflush(f_out8);
      fflush(f_out9);
      fflush(f_out10);
      fflush(f_out11);
      fflush(f_out12);
      fflush(f_out13);
      fflush(f_out14);
      }
    
    input_att = _get_double("input_att");
    if (traces) {
      fprintf(f_in1, "%f\n", input_att);
      fflush(f_in1);
      }
    
    input_alt = _get_double("input_alt");
    if (traces) {
      fprintf(f_in2, "%f\n", input_alt);
      fflush(f_in2);
      }
    
    ov_spec_bound = _get_double("ov_spec_bound");
    if (traces) {
      fprintf(f_in3, "%f\n", ov_spec_bound);
      fflush(f_in3);
      }
    
    rt_spec_bound = _get_double("rt_spec_bound");
    if (traces) {
      fprintf(f_in4, "%f\n", rt_spec_bound);
      fflush(f_in4);
      }
    
    st_spec_bound = _get_double("st_spec_bound");
    if (traces) {
      fprintf(f_in5, "%f\n", st_spec_bound);
      fflush(f_in5);
      }
    
    ss_spec_bound = _get_double("ss_spec_bound");
    if (traces) {
      fprintf(f_in6, "%f\n", ss_spec_bound);
      fflush(f_in6);
      }
    
    APE_spec_bound = _get_double("APE_spec_bound");
    if (traces) {
      fprintf(f_in7, "%f\n", APE_spec_bound);
      fflush(f_in7);
      }
    
    MPE_spec_bound = _get_double("MPE_spec_bound");
    if (traces) {
      fprintf(f_in8, "%f\n", MPE_spec_bound);
      fflush(f_in8);
      }
    
    RPE_spec_bound = _get_double("RPE_spec_bound");
    if (traces) {
      fprintf(f_in9, "%f\n", RPE_spec_bound);
      fflush(f_in9);
      }
    
    PDE_spec_bound = _get_double("PDE_spec_bound");
    if (traces) {
      fprintf(f_in10, "%f\n", PDE_spec_bound);
      fflush(f_in10);
      }
    
    trigger_ESA_att = _get_bool("trigger_ESA_att");
    if (traces) {
      fprintf(f_in11, "%i\n", trigger_ESA_att);
      fflush(f_in11);
      }
    
    rt_spec_time = _get_int("rt_spec_time");
    if (traces) {
      fprintf(f_in12, "%d\n", rt_spec_time);
      fflush(f_in12);
      }
    
    st_spec_time = _get_int("st_spec_time");
    if (traces) {
      fprintf(f_in13, "%d\n", st_spec_time);
      fflush(f_in13);
      }
    
    inv_Ts = _get_int("inv_Ts");
    if (traces) {
      fprintf(f_in14, "%d\n", inv_Ts);
      fflush(f_in14);
      }
    
    b = _get_int("b");
    if (traces) {
      fprintf(f_in15, "%d\n", b);
      fflush(f_in15);
      }
    
    quadcopter_model_Lustre_STL_PP_step (input_att, input_alt, ov_spec_bound, rt_spec_bound, st_spec_bound, ss_spec_bound, APE_spec_bound, MPE_spec_bound, RPE_spec_bound, PDE_spec_bound, trigger_ESA_att, rt_spec_time, st_spec_time, inv_Ts, b, &__time_step, &eval_ov_att, &trigger_ov_att, &eval_rt_att, &trigger_rt_att, &eval_st_att, &trigger_st_att, &eval_ss_att, &trigger_ss_att, &eval_APE_att, &eval_MPE_att, &eval_RPE_att, &eval_PDE_att, &Attitudecontrol_1, &main_mem);
    _put_double("__time_step", __time_step, 15);
    if (traces) {
      fprintf(f_out1, "%.*f\n", 15, __time_step);
      fflush(f_out1);
      }
    ;
    _put_bool("eval_ov_att", eval_ov_att);
    if (traces) {
      fprintf(f_out2, "%i\n", eval_ov_att);
      fflush(f_out2);
      }
    ;
    _put_bool("trigger_ov_att", trigger_ov_att);
    if (traces) {
      fprintf(f_out3, "%i\n", trigger_ov_att);
      fflush(f_out3);
      }
    ;
    _put_bool("eval_rt_att", eval_rt_att);
    if (traces) {
      fprintf(f_out4, "%i\n", eval_rt_att);
      fflush(f_out4);
      }
    ;
    _put_bool("trigger_rt_att", trigger_rt_att);
    if (traces) {
      fprintf(f_out5, "%i\n", trigger_rt_att);
      fflush(f_out5);
      }
    ;
    _put_bool("eval_st_att", eval_st_att);
    if (traces) {
      fprintf(f_out6, "%i\n", eval_st_att);
      fflush(f_out6);
      }
    ;
    _put_bool("trigger_st_att", trigger_st_att);
    if (traces) {
      fprintf(f_out7, "%i\n", trigger_st_att);
      fflush(f_out7);
      }
    ;
    _put_bool("eval_ss_att", eval_ss_att);
    if (traces) {
      fprintf(f_out8, "%i\n", eval_ss_att);
      fflush(f_out8);
      }
    ;
    _put_bool("trigger_ss_att", trigger_ss_att);
    if (traces) {
      fprintf(f_out9, "%i\n", trigger_ss_att);
      fflush(f_out9);
      }
    ;
    _put_bool("eval_APE_att", eval_APE_att);
    if (traces) {
      fprintf(f_out10, "%i\n", eval_APE_att);
      fflush(f_out10);
      }
    ;
    _put_bool("eval_MPE_att", eval_MPE_att);
    if (traces) {
      fprintf(f_out11, "%i\n", eval_MPE_att);
      fflush(f_out11);
      }
    ;
    _put_bool("eval_RPE_att", eval_RPE_att);
    if (traces) {
      fprintf(f_out12, "%i\n", eval_RPE_att);
      fflush(f_out12);
      }
    ;
    _put_bool("eval_PDE_att", eval_PDE_att);
    if (traces) {
      fprintf(f_out13, "%i\n", eval_PDE_att);
      fflush(f_out13);
      }
    ;
    _put_double("Attitudecontrol_1", Attitudecontrol_1, 15);
    if (traces) {
      fprintf(f_out14, "%.*f\n", 15, Attitudecontrol_1);
      fflush(f_out14);
      }
    ;
    
  }
  
  
  return 1;
}
