/* C code generated by lustrec
   Version number 1.7
   Code is C99 compliant
   Using (double) floating-point numbers */
   
#ifndef _UAV_WITH_PROP_OBSERV
#define _UAV_WITH_PROP_OBSERV

/* Imports standard library */
#include <stdint.h>
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Structs declarations */
struct PDE_verification_5_mem;
struct quadcopter_model_Lustre_STL_PP_mem;
struct RPE_verification_5_mem;
struct MPE_verification_5_mem;
struct steady_state_verification_mem;
struct settling_time_verification_mem;
struct rise_time_verification_mem;
struct overshoot_verification_mem;
struct RPE_verification_5_simple_mem;
struct PDE_verification_5_simple_mem;
struct MPE_verification_5_simple_mem;
struct Attitudecontrol_496_001_mem;
struct Altitudecontrol_156_003_mem;
struct APE_verification_mem;
struct trigger_on_settling_time_mem;
struct always_3v_var_mem;
struct trigger_on_rise_time_mem;
struct trigger_off_rise_time_mem;
struct eventually_3v_var_mem;
struct trigger_on_overshoot_mem;
struct trigger_off_overshoot_mem;
struct Plant_688_001_mem;
struct Controller_I_PD_501_000_mem;
struct Plant_402_001_mem;
struct Controller_I_PD_161_003_mem;
struct always_true_var_mem;
struct always_false_var_mem;
struct absolute_value_mem;
struct eventually_true_var_mem;
struct eventually_false_var_mem;
struct signal_crossing_mem;
struct Gain3_4197_001_mem;
struct Gain2_4181_001_mem;
struct Gain1_707_001_mem;
struct Gain4_562_001_mem;
struct Gain3_546_001_mem;
struct Gain2_529_001_mem;
struct Gain1_513_000_mem;
struct Gain3_443_001_mem;
struct Gain2_427_001_mem;
struct Gain1_411_000_mem;
struct Gain4_343_001_mem;
struct Gain3_327_001_mem;
struct Gain2_311_001_mem;
struct Gain1_295_004_mem;
struct forall_a_mem;
struct timeab_var_mem;
struct forall_a_var_mem;
struct kind2_times_mem;
struct exist_mem;
struct timeab_tmp_var_mem;
struct exist_var_mem;
struct min_mem;

/* Nodes declarations */
extern void PDE_verification_5_reset (struct PDE_verification_5_mem *self);

extern void PDE_verification_5_init (struct PDE_verification_5_mem *self);

extern void PDE_verification_5_clear (struct PDE_verification_5_mem *self);

extern void PDE_verification_5_step (double ref, double sys, double bound,
                                     _Bool p_trigger, int interval,
                                     double e_11, double e_12, double e_13,
                                     double e_14, double e_15, double e_21,
                                     double e_22, double e_23, double e_24,
                                     double e_25, 
                                     _Bool (*eval),
                                     struct PDE_verification_5_mem *self);

extern void quadcopter_model_Lustre_STL_PP_reset (struct quadcopter_model_Lustre_STL_PP_mem *self);

extern void quadcopter_model_Lustre_STL_PP_init (struct quadcopter_model_Lustre_STL_PP_mem *self);

extern void quadcopter_model_Lustre_STL_PP_clear (struct quadcopter_model_Lustre_STL_PP_mem *self);

extern void quadcopter_model_Lustre_STL_PP_step (double input_att,
                                                 double input_alt,
                                                 double ov_spec_bound,
                                                 double rt_spec_bound,
                                                 double st_spec_bound,
                                                 double ss_spec_bound,
                                                 double APE_spec_bound,
                                                 double MPE_spec_bound,
                                                 double RPE_spec_bound,
                                                 double PDE_spec_bound,
                                                 _Bool trigger_ESA_att,
                                                 int rt_spec_time,
                                                 int st_spec_time,
                                                 int inv_Ts, int b, 
                                                 double (*__time_step),
                                                 _Bool (*eval_ov_att),
                                                 _Bool (*trigger_ov_att),
                                                 _Bool (*eval_rt_att),
                                                 _Bool (*trigger_rt_att),
                                                 _Bool (*eval_st_att),
                                                 _Bool (*trigger_st_att),
                                                 _Bool (*eval_ss_att),
                                                 _Bool (*trigger_ss_att),
                                                 _Bool (*eval_APE_att),
                                                 _Bool (*eval_MPE_att),
                                                 _Bool (*eval_RPE_att),
                                                 _Bool (*eval_PDE_att),
                                                 double (*Attitudecontrol_1),
                                                 struct quadcopter_model_Lustre_STL_PP_mem *self);

extern void RPE_verification_5_reset (struct RPE_verification_5_mem *self);

extern void RPE_verification_5_init (struct RPE_verification_5_mem *self);

extern void RPE_verification_5_clear (struct RPE_verification_5_mem *self);

extern void RPE_verification_5_step (double ref, double sys, double bound,
                                     _Bool p_trigger, double e_1, double e_2,
                                     double e_3, double e_4, double e_5, 
                                     _Bool (*eval),
                                     struct RPE_verification_5_mem *self);

extern void MPE_verification_5_reset (struct MPE_verification_5_mem *self);

extern void MPE_verification_5_init (struct MPE_verification_5_mem *self);

extern void MPE_verification_5_clear (struct MPE_verification_5_mem *self);

extern void MPE_verification_5_step (double ref, double sys, double bound,
                                     _Bool p_trigger, double e_1, double e_2,
                                     double e_3, double e_4, double e_5, 
                                     _Bool (*eval),
                                     struct MPE_verification_5_mem *self);

extern void steady_state_verification_reset (struct steady_state_verification_mem *self);

extern void steady_state_verification_init (struct steady_state_verification_mem *self);

extern void steady_state_verification_clear (struct steady_state_verification_mem *self);

extern void steady_state_verification_step (double ref, double sys,
                                            double bound, int time_step,
                                            int b, 
                                            _Bool (*trigger), _Bool (*eval),
                                            struct steady_state_verification_mem *self);

extern void settling_time_verification_reset (struct settling_time_verification_mem *self);

extern void settling_time_verification_init (struct settling_time_verification_mem *self);

extern void settling_time_verification_clear (struct settling_time_verification_mem *self);

extern void settling_time_verification_step (double ref, double sys,
                                             double bound,
                                             int time_st_observ,
                                             int time_step, int b, 
                                             _Bool (*trigger), _Bool (*eval),
                                             struct settling_time_verification_mem *self);

extern void rise_time_verification_reset (struct rise_time_verification_mem *self);

extern void rise_time_verification_init (struct rise_time_verification_mem *self);

extern void rise_time_verification_clear (struct rise_time_verification_mem *self);

extern void rise_time_verification_step (double ref, double sys,
                                         double bound, int time_rt,
                                         int time_step, 
                                         _Bool (*trigger), _Bool (*eval),
                                         struct rise_time_verification_mem *self);

extern void overshoot_verification_reset (struct overshoot_verification_mem *self);

extern void overshoot_verification_init (struct overshoot_verification_mem *self);

extern void overshoot_verification_clear (struct overshoot_verification_mem *self);

extern void overshoot_verification_step (double ref, double sys,
                                         double bound, 
                                         _Bool (*trigger), _Bool (*eval),
                                         struct overshoot_verification_mem *self);

extern void RPE_verification_5_simple_reset (struct RPE_verification_5_simple_mem *self);

extern void RPE_verification_5_simple_init (struct RPE_verification_5_simple_mem *self);

extern void RPE_verification_5_simple_clear (struct RPE_verification_5_simple_mem *self);

extern void RPE_verification_5_simple_step (double ref, double sys,
                                            double bound, _Bool p_trigger, 
                                            _Bool (*eval),
                                            struct RPE_verification_5_simple_mem *self);

extern void PDE_verification_5_simple_reset (struct PDE_verification_5_simple_mem *self);

extern void PDE_verification_5_simple_init (struct PDE_verification_5_simple_mem *self);

extern void PDE_verification_5_simple_clear (struct PDE_verification_5_simple_mem *self);

extern void PDE_verification_5_simple_step (double ref, double sys,
                                            double bound, _Bool p_trigger, 
                                            _Bool (*eval),
                                            struct PDE_verification_5_simple_mem *self);

extern void MPE_verification_5_simple_reset (struct MPE_verification_5_simple_mem *self);

extern void MPE_verification_5_simple_init (struct MPE_verification_5_simple_mem *self);

extern void MPE_verification_5_simple_clear (struct MPE_verification_5_simple_mem *self);

extern void MPE_verification_5_simple_step (double ref, double sys,
                                            double bound, _Bool p_trigger, 
                                            _Bool (*eval),
                                            struct MPE_verification_5_simple_mem *self);

extern void Attitudecontrol_496_001_reset (struct Attitudecontrol_496_001_mem *self);

extern void Attitudecontrol_496_001_init (struct Attitudecontrol_496_001_mem *self);

extern void Attitudecontrol_496_001_clear (struct Attitudecontrol_496_001_mem *self);

extern void Attitudecontrol_496_001_step (double input_1, double __time_step,
                                          int __nb_step, 
                                          double (*yp_att_1),
                                          struct Attitudecontrol_496_001_mem *self);

extern void Altitudecontrol_156_003_reset (struct Altitudecontrol_156_003_mem *self);

extern void Altitudecontrol_156_003_init (struct Altitudecontrol_156_003_mem *self);

extern void Altitudecontrol_156_003_clear (struct Altitudecontrol_156_003_mem *self);

extern void Altitudecontrol_156_003_step (double input_1, double __time_step,
                                          int __nb_step, 
                                          double (*yp_alt_1),
                                          struct Altitudecontrol_156_003_mem *self);

extern void APE_verification_reset (struct APE_verification_mem *self);

extern void APE_verification_init (struct APE_verification_mem *self);

extern void APE_verification_clear (struct APE_verification_mem *self);

extern void APE_verification_step (double ref, double sys, double bound,
                                   _Bool p_trigger, 
                                   _Bool (*eval),
                                   struct APE_verification_mem *self);

extern void trigger_on_settling_time_reset (struct trigger_on_settling_time_mem *self);

extern void trigger_on_settling_time_init (struct trigger_on_settling_time_mem *self);

extern void trigger_on_settling_time_clear (struct trigger_on_settling_time_mem *self);

extern void trigger_on_settling_time_step (_Bool p_trigger, double ref,
                                           double sys, double bound, 
                                           _Bool (*trigger),
                                           struct trigger_on_settling_time_mem *self);

extern void always_3v_var_reset (struct always_3v_var_mem *self);

extern void always_3v_var_init (struct always_3v_var_mem *self);

extern void always_3v_var_clear (struct always_3v_var_mem *self);

extern void always_3v_var_step (int a, int b, _Bool phi, 
                                _Bool (*output_alw_true),
                                _Bool (*output_alw_false),
                                struct always_3v_var_mem *self);

extern void trigger_on_rise_time_reset (struct trigger_on_rise_time_mem *self);

extern void trigger_on_rise_time_init (struct trigger_on_rise_time_mem *self);

extern void trigger_on_rise_time_clear (struct trigger_on_rise_time_mem *self);

extern void trigger_on_rise_time_step (_Bool p_trigger, double ref,
                                       double sys, double bound, 
                                       _Bool (*trigger),
                                       struct trigger_on_rise_time_mem *self);

extern void trigger_off_rise_time_reset (struct trigger_off_rise_time_mem *self);

extern void trigger_off_rise_time_init (struct trigger_off_rise_time_mem *self);

extern void trigger_off_rise_time_clear (struct trigger_off_rise_time_mem *self);

extern void trigger_off_rise_time_step (_Bool p_trigger, double ref,
                                        double sys, double bound, 
                                        _Bool (*trigger),
                                        struct trigger_off_rise_time_mem *self);

extern void eventually_3v_var_reset (struct eventually_3v_var_mem *self);

extern void eventually_3v_var_init (struct eventually_3v_var_mem *self);

extern void eventually_3v_var_clear (struct eventually_3v_var_mem *self);

extern void eventually_3v_var_step (int a, int b, _Bool phi, 
                                    _Bool (*output_ev_true),
                                    _Bool (*output_ev_false),
                                    struct eventually_3v_var_mem *self);

extern void trigger_on_overshoot_reset (struct trigger_on_overshoot_mem *self);

extern void trigger_on_overshoot_init (struct trigger_on_overshoot_mem *self);

extern void trigger_on_overshoot_clear (struct trigger_on_overshoot_mem *self);

extern void trigger_on_overshoot_step (_Bool p_trigger, double ref,
                                       double sys, 
                                       _Bool (*trigger),
                                       struct trigger_on_overshoot_mem *self);

extern void trigger_off_overshoot_reset (struct trigger_off_overshoot_mem *self);

extern void trigger_off_overshoot_init (struct trigger_off_overshoot_mem *self);

extern void trigger_off_overshoot_clear (struct trigger_off_overshoot_mem *self);

extern void trigger_off_overshoot_step (_Bool p_trigger, double ref,
                                        double sys, 
                                        _Bool (*trigger),
                                        struct trigger_off_overshoot_mem *self);

extern void Plant_688_001_reset (struct Plant_688_001_mem *self);

extern void Plant_688_001_init (struct Plant_688_001_mem *self);

extern void Plant_688_001_clear (struct Plant_688_001_mem *self);

extern void Plant_688_001_step (double xp_in_1, double xp_in_2, double yc_1,
                                double __time_step, int __nb_step, 
                                double (*xp_out_1), double (*xp_out_2),
                                double (*yp_1),
                                struct Plant_688_001_mem *self);

extern void Controller_I_PD_501_000_reset (struct Controller_I_PD_501_000_mem *self);

extern void Controller_I_PD_501_000_init (struct Controller_I_PD_501_000_mem *self);

extern void Controller_I_PD_501_000_clear (struct Controller_I_PD_501_000_mem *self);

extern void Controller_I_PD_501_000_step (double u_1, double xc_in_1,
                                          double xc_in_2, double yp_1,
                                          double __time_step, int __nb_step, 
                                          double (*xc_out_1),
                                          double (*xc_out_2), double (*yc_1),
                                          struct Controller_I_PD_501_000_mem *self);

extern void Plant_402_001_reset (struct Plant_402_001_mem *self);

extern void Plant_402_001_init (struct Plant_402_001_mem *self);

extern void Plant_402_001_clear (struct Plant_402_001_mem *self);

extern void Plant_402_001_step (double xp_in_1, double xp_in_2, double yc_1,
                                double __time_step, int __nb_step, 
                                double (*xp_out_1), double (*xp_out_2),
                                double (*yp_1),
                                struct Plant_402_001_mem *self);

extern void Controller_I_PD_161_003_reset (struct Controller_I_PD_161_003_mem *self);

extern void Controller_I_PD_161_003_init (struct Controller_I_PD_161_003_mem *self);

extern void Controller_I_PD_161_003_clear (struct Controller_I_PD_161_003_mem *self);

extern void Controller_I_PD_161_003_step (double u_1, double xc_in_1,
                                          double xc_in_2, double yp_1,
                                          double __time_step, int __nb_step, 
                                          double (*xc_out_1),
                                          double (*xc_out_2), double (*yc_1),
                                          struct Controller_I_PD_161_003_mem *self);

extern void always_true_var_reset (struct always_true_var_mem *self);

extern void always_true_var_init (struct always_true_var_mem *self);

extern void always_true_var_clear (struct always_true_var_mem *self);

extern void always_true_var_step (int a, int b, _Bool phi, 
                                  _Bool (*output_alw_true),
                                  struct always_true_var_mem *self);

extern void always_false_var_reset (struct always_false_var_mem *self);

extern void always_false_var_init (struct always_false_var_mem *self);

extern void always_false_var_clear (struct always_false_var_mem *self);

extern void always_false_var_step (int a, int b, _Bool phi, 
                                   _Bool (*output_alw_false),
                                   struct always_false_var_mem *self);

extern void absolute_value_reset (struct absolute_value_mem *self);

extern void absolute_value_init (struct absolute_value_mem *self);

extern void absolute_value_clear (struct absolute_value_mem *self);

extern void absolute_value_step (double x, 
                                 double (*abs),
                                 struct absolute_value_mem *self);

extern void eventually_true_var_reset (struct eventually_true_var_mem *self);

extern void eventually_true_var_init (struct eventually_true_var_mem *self);

extern void eventually_true_var_clear (struct eventually_true_var_mem *self);

extern void eventually_true_var_step (int a, int b, _Bool phi, 
                                      _Bool (*output_ev_true),
                                      struct eventually_true_var_mem *self);

extern void eventually_false_var_reset (struct eventually_false_var_mem *self);

extern void eventually_false_var_init (struct eventually_false_var_mem *self);

extern void eventually_false_var_clear (struct eventually_false_var_mem *self);

extern void eventually_false_var_step (int a, int b, _Bool phi, 
                                       _Bool (*output_ev_false),
                                       struct eventually_false_var_mem *self);

extern void signal_crossing_reset (struct signal_crossing_mem *self);

extern void signal_crossing_init (struct signal_crossing_mem *self);

extern void signal_crossing_clear (struct signal_crossing_mem *self);

extern void signal_crossing_step (double ref, double sys, 
                                  _Bool (*crossing),
                                  struct signal_crossing_mem *self);

extern void Gain3_4197_001_reset (struct Gain3_4197_001_mem *self);

extern void Gain3_4197_001_init (struct Gain3_4197_001_mem *self);

extern void Gain3_4197_001_clear (struct Gain3_4197_001_mem *self);

extern void Gain3_4197_001_step (double u_1, double u_2, double __time_step,
                                 int __nb_step, 
                                 double (*Out1_1),
                                 struct Gain3_4197_001_mem *self);

extern void Gain2_4181_001_reset (struct Gain2_4181_001_mem *self);

extern void Gain2_4181_001_init (struct Gain2_4181_001_mem *self);

extern void Gain2_4181_001_clear (struct Gain2_4181_001_mem *self);

extern void Gain2_4181_001_step (double u_1, double __time_step,
                                 int __nb_step, 
                                 double (*Out1_1), double (*Out1_2),
                                 struct Gain2_4181_001_mem *self);

extern void Gain1_707_001_reset (struct Gain1_707_001_mem *self);

extern void Gain1_707_001_init (struct Gain1_707_001_mem *self);

extern void Gain1_707_001_clear (struct Gain1_707_001_mem *self);

extern void Gain1_707_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain1_707_001_mem *self);

extern void Gain4_562_001_reset (struct Gain4_562_001_mem *self);

extern void Gain4_562_001_init (struct Gain4_562_001_mem *self);

extern void Gain4_562_001_clear (struct Gain4_562_001_mem *self);

extern void Gain4_562_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1),
                                struct Gain4_562_001_mem *self);

extern void Gain3_546_001_reset (struct Gain3_546_001_mem *self);

extern void Gain3_546_001_init (struct Gain3_546_001_mem *self);

extern void Gain3_546_001_clear (struct Gain3_546_001_mem *self);

extern void Gain3_546_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1),
                                struct Gain3_546_001_mem *self);

extern void Gain2_529_001_reset (struct Gain2_529_001_mem *self);

extern void Gain2_529_001_init (struct Gain2_529_001_mem *self);

extern void Gain2_529_001_clear (struct Gain2_529_001_mem *self);

extern void Gain2_529_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain2_529_001_mem *self);

extern void Gain1_513_000_reset (struct Gain1_513_000_mem *self);

extern void Gain1_513_000_init (struct Gain1_513_000_mem *self);

extern void Gain1_513_000_clear (struct Gain1_513_000_mem *self);

extern void Gain1_513_000_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain1_513_000_mem *self);

extern void Gain3_443_001_reset (struct Gain3_443_001_mem *self);

extern void Gain3_443_001_init (struct Gain3_443_001_mem *self);

extern void Gain3_443_001_clear (struct Gain3_443_001_mem *self);

extern void Gain3_443_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1),
                                struct Gain3_443_001_mem *self);

extern void Gain2_427_001_reset (struct Gain2_427_001_mem *self);

extern void Gain2_427_001_init (struct Gain2_427_001_mem *self);

extern void Gain2_427_001_clear (struct Gain2_427_001_mem *self);

extern void Gain2_427_001_step (double u_1, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain2_427_001_mem *self);

extern void Gain1_411_000_reset (struct Gain1_411_000_mem *self);

extern void Gain1_411_000_init (struct Gain1_411_000_mem *self);

extern void Gain1_411_000_clear (struct Gain1_411_000_mem *self);

extern void Gain1_411_000_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain1_411_000_mem *self);

extern void Gain4_343_001_reset (struct Gain4_343_001_mem *self);

extern void Gain4_343_001_init (struct Gain4_343_001_mem *self);

extern void Gain4_343_001_clear (struct Gain4_343_001_mem *self);

extern void Gain4_343_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1),
                                struct Gain4_343_001_mem *self);

extern void Gain3_327_001_reset (struct Gain3_327_001_mem *self);

extern void Gain3_327_001_init (struct Gain3_327_001_mem *self);

extern void Gain3_327_001_clear (struct Gain3_327_001_mem *self);

extern void Gain3_327_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1),
                                struct Gain3_327_001_mem *self);

extern void Gain2_311_001_reset (struct Gain2_311_001_mem *self);

extern void Gain2_311_001_init (struct Gain2_311_001_mem *self);

extern void Gain2_311_001_clear (struct Gain2_311_001_mem *self);

extern void Gain2_311_001_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain2_311_001_mem *self);

extern void Gain1_295_004_reset (struct Gain1_295_004_mem *self);

extern void Gain1_295_004_init (struct Gain1_295_004_mem *self);

extern void Gain1_295_004_clear (struct Gain1_295_004_mem *self);

extern void Gain1_295_004_step (double u_1, double u_2, double __time_step,
                                int __nb_step, 
                                double (*Out1_1), double (*Out1_2),
                                struct Gain1_295_004_mem *self);

extern void forall_a_reset (struct forall_a_mem *self);

extern void forall_a_init (struct forall_a_mem *self);

extern void forall_a_clear (struct forall_a_mem *self);

extern void forall_a_step (_Bool inside_time_interval, _Bool prop, 
                           _Bool (*output),
                           struct forall_a_mem *self);

extern void timeab_var_reset (struct timeab_var_mem *self);

extern void timeab_var_init (struct timeab_var_mem *self);

extern void timeab_var_clear (struct timeab_var_mem *self);

extern void timeab_var_step (int a, int b, 
                             _Bool (*inside_time_interval),
                             struct timeab_var_mem *self);

extern void forall_a_var_reset (struct forall_a_var_mem *self);

extern void forall_a_var_init (struct forall_a_var_mem *self);

extern void forall_a_var_clear (struct forall_a_var_mem *self);

extern void forall_a_var_step (_Bool inside_time_interval, _Bool prop, 
                               _Bool (*output),
                               struct forall_a_var_mem *self);

extern void kind2_times_reset (struct kind2_times_mem *self);

extern void kind2_times_init (struct kind2_times_mem *self);

extern void kind2_times_clear (struct kind2_times_mem *self);

extern void kind2_times_step (double x1, double x2, 
                              double (*prod),
                              struct kind2_times_mem *self);

extern void exist_reset (struct exist_mem *self);

extern void exist_init (struct exist_mem *self);

extern void exist_clear (struct exist_mem *self);

extern void exist_step (_Bool inside_time_interval, _Bool prop, 
                        _Bool (*output),
                        struct exist_mem *self);

extern void timeab_tmp_var_reset (struct timeab_tmp_var_mem *self);

extern void timeab_tmp_var_init (struct timeab_tmp_var_mem *self);

extern void timeab_tmp_var_clear (struct timeab_tmp_var_mem *self);

extern void timeab_tmp_var_step (int a, int b, 
                                 int (*internal_clk),
                                 _Bool (*inside_time_interval),
                                 struct timeab_tmp_var_mem *self);

extern void exist_var_reset (struct exist_var_mem *self);

extern void exist_var_init (struct exist_var_mem *self);

extern void exist_var_clear (struct exist_var_mem *self);

extern void exist_var_step (_Bool inside_time_interval, _Bool prop, 
                            _Bool (*output),
                            struct exist_var_mem *self);

extern void min_reset (struct min_mem *self);

extern void min_init (struct min_mem *self);

extern void min_clear (struct min_mem *self);

extern void min_step (int a, int b, 
                      int (*valeur_min),
                      struct min_mem *self);


#endif

