/* C code generated by lustrec
   Version number 1.7
   Code is C99 compliant
   Using (double) floating-point numbers */
   
#ifndef _UAV_WITH_PROP_OBSERV_alloc
#define _UAV_WITH_PROP_OBSERV_alloc

/* Import header from UAV_with_prop_observ */
#include "UAV_with_prop_observ.h"

/* Import dependencies */

/* Struct definitions */
struct min_mem {};
struct exist_var_mem {};
struct timeab_tmp_var_mem {struct timeab_tmp_var_reg {int __timeab_tmp_var_2;
                                                      } _reg; 
                           struct _arrow_mem *ni_149;
                           struct min_mem *ni_148;
                           };
struct exist_mem {struct exist_reg {_Bool __exist_2;
                                    } _reg; 
                  struct _arrow_mem *ni_147;
                  };
struct kind2_times_mem {};
struct forall_a_var_mem {struct exist_var_mem *ni_146;
                         };
struct timeab_var_mem {struct timeab_tmp_var_mem *ni_145;
                       };
struct forall_a_mem {struct exist_mem *ni_144;
                     };
struct Gain1_295_004_mem {struct kind2_times_mem *ni_143;
                          struct kind2_times_mem *ni_142;
                          struct kind2_times_mem *ni_141;
                          struct kind2_times_mem *ni_140;
                          };
struct Gain2_311_001_mem {struct kind2_times_mem *ni_139;
                          struct kind2_times_mem *ni_138;
                          struct kind2_times_mem *ni_137;
                          struct kind2_times_mem *ni_136;
                          };
struct Gain3_327_001_mem {struct kind2_times_mem *ni_135;
                          struct kind2_times_mem *ni_134;
                          };
struct Gain4_343_001_mem {struct kind2_times_mem *ni_133;
                          struct kind2_times_mem *ni_132;
                          };
struct Gain1_411_000_mem {struct kind2_times_mem *ni_131;
                          struct kind2_times_mem *ni_130;
                          struct kind2_times_mem *ni_129;
                          struct kind2_times_mem *ni_128;
                          };
struct Gain2_427_001_mem {struct kind2_times_mem *ni_127;
                          struct kind2_times_mem *ni_126;
                          };
struct Gain3_443_001_mem {struct kind2_times_mem *ni_125;
                          struct kind2_times_mem *ni_124;
                          };
struct Gain1_513_000_mem {struct kind2_times_mem *ni_123;
                          struct kind2_times_mem *ni_122;
                          struct kind2_times_mem *ni_121;
                          struct kind2_times_mem *ni_120;
                          };
struct Gain2_529_001_mem {struct kind2_times_mem *ni_119;
                          struct kind2_times_mem *ni_118;
                          struct kind2_times_mem *ni_117;
                          struct kind2_times_mem *ni_116;
                          };
struct Gain3_546_001_mem {struct kind2_times_mem *ni_115;
                          struct kind2_times_mem *ni_114;
                          };
struct Gain4_562_001_mem {struct kind2_times_mem *ni_113;
                          struct kind2_times_mem *ni_112;
                          };
struct Gain1_707_001_mem {struct kind2_times_mem *ni_111;
                          struct kind2_times_mem *ni_110;
                          struct kind2_times_mem *ni_109;
                          struct kind2_times_mem *ni_108;
                          };
struct Gain2_4181_001_mem {struct kind2_times_mem *ni_107;
                           struct kind2_times_mem *ni_106;
                           };
struct Gain3_4197_001_mem {struct kind2_times_mem *ni_105;
                           struct kind2_times_mem *ni_104;
                           };
struct signal_crossing_mem {struct signal_crossing_reg {double __signal_crossing_2;
                                                        double __signal_crossing_3;
                                                        } _reg; 
                            struct _arrow_mem *ni_103;
                            };
struct eventually_false_var_mem {struct eventually_false_var_reg {int __eventually_false_var_4;
                                                                  } _reg; 
                                 struct forall_a_var_mem *ni_99;
                                 struct _arrow_mem *ni_102;
                                 struct min_mem *ni_101;
                                 struct timeab_var_mem *ni_100;
                                 };
struct eventually_true_var_mem {struct timeab_var_mem *ni_98;
                                struct exist_var_mem *ni_97;
                                };
struct absolute_value_mem {};
struct always_false_var_mem {struct always_false_var_reg {int __always_false_var_3;
                                                          } _reg; 
                             struct timeab_var_mem *ni_96;
                             struct exist_mem *ni_95;
                             struct _arrow_mem *ni_94;
                             struct min_mem *ni_93;
                             };
struct always_true_var_mem {struct always_true_var_reg {int __always_true_var_4;
                                                        } _reg; 
                            struct _arrow_mem *ni_92;
                            struct min_mem *ni_91;
                            struct timeab_var_mem *ni_90;
                            struct forall_a_mem *ni_89;
                            };
struct Controller_I_PD_161_003_mem {struct Gain4_343_001_mem *ni_88;
                                    struct Gain3_327_001_mem *ni_87;
                                    struct Gain2_311_001_mem *ni_86;
                                    struct Gain1_295_004_mem *ni_85;
                                    };
struct Plant_402_001_mem {struct Gain3_443_001_mem *ni_84;
                          struct Gain2_427_001_mem *ni_83;
                          struct Gain1_411_000_mem *ni_82;
                          };
struct Controller_I_PD_501_000_mem {struct Gain4_562_001_mem *ni_81;
                                    struct Gain3_546_001_mem *ni_80;
                                    struct Gain2_529_001_mem *ni_79;
                                    struct Gain1_513_000_mem *ni_78;
                                    };
struct Plant_688_001_mem {struct Gain3_4197_001_mem *ni_77;
                          struct Gain2_4181_001_mem *ni_76;
                          struct Gain1_707_001_mem *ni_75;
                          };
struct trigger_off_overshoot_mem {struct signal_crossing_mem *ni_74;
                                  };
struct trigger_on_overshoot_mem {struct signal_crossing_mem *ni_73;
                                 };
struct eventually_3v_var_mem {struct eventually_true_var_mem *ni_72;
                              struct eventually_false_var_mem *ni_71;
                              };
struct trigger_off_rise_time_mem {struct trigger_off_rise_time_reg {double __trigger_off_rise_time_3;
                                                                    } _reg; 
                                  struct _arrow_mem *ni_70;
                                  struct absolute_value_mem *ni_69;
                                  };
struct trigger_on_rise_time_mem {struct trigger_on_rise_time_reg {double __trigger_on_rise_time_3;
                                                                  } _reg; 
                                 struct absolute_value_mem *ni_68;
                                 struct absolute_value_mem *ni_67;
                                 struct _arrow_mem *ni_66;
                                 };
struct always_3v_var_mem {struct always_true_var_mem *ni_65;
                          struct always_false_var_mem *ni_64;
                          };
struct trigger_on_settling_time_mem {struct trigger_on_settling_time_reg {
                                     double __trigger_on_settling_time_3;
                                     } _reg; 
                                     struct absolute_value_mem *ni_63;
                                     struct _arrow_mem *ni_62;
                                     };
struct APE_verification_mem {struct absolute_value_mem *ni_61;
                             };
struct Altitudecontrol_156_003_mem {struct Altitudecontrol_156_003_reg {
                                    double __Altitudecontrol_156_003_2;
                                    double __Altitudecontrol_156_003_3;
                                    double __Altitudecontrol_156_003_4;
                                    double __Altitudecontrol_156_003_5;
                                    double __Altitudecontrol_156_003_6;
                                    } _reg; 
                                    struct _arrow_mem *ni_60;
                                    struct Controller_I_PD_161_003_mem *ni_59;
                                    struct Plant_402_001_mem *ni_58;
                                    };
struct Attitudecontrol_496_001_mem {struct Attitudecontrol_496_001_reg {
                                    double __Attitudecontrol_496_001_2;
                                    double __Attitudecontrol_496_001_3;
                                    double __Attitudecontrol_496_001_4;
                                    double __Attitudecontrol_496_001_5;
                                    double __Attitudecontrol_496_001_6;
                                    } _reg; 
                                    struct _arrow_mem *ni_57;
                                    struct Controller_I_PD_501_000_mem *ni_56;
                                    struct Plant_688_001_mem *ni_55;
                                    };
struct MPE_verification_5_simple_mem {struct MPE_verification_5_simple_reg {
                                      double __MPE_verification_5_simple_10;
                                      int __MPE_verification_5_simple_4;
                                      double __MPE_verification_5_simple_7;
                                      double __MPE_verification_5_simple_8;
                                      double __MPE_verification_5_simple_9;
                                      } _reg; 
                                      struct _arrow_mem *ni_54;
                                      struct min_mem *ni_53;
                                      struct absolute_value_mem *ni_52;
                                      struct absolute_value_mem *ni_51;
                                      };
struct PDE_verification_5_simple_mem {struct PDE_verification_5_simple_reg {
                                      double __PDE_verification_5_simple_10;
                                      double __PDE_verification_5_simple_11;
                                      double __PDE_verification_5_simple_12;
                                      double __PDE_verification_5_simple_13;
                                      double __PDE_verification_5_simple_14;
                                      double __PDE_verification_5_simple_15;
                                      double __PDE_verification_5_simple_16;
                                      int __PDE_verification_5_simple_4;
                                      double __PDE_verification_5_simple_6;
                                      double __PDE_verification_5_simple_7;
                                      double __PDE_verification_5_simple_8;
                                      double __PDE_verification_5_simple_9;
                                      } _reg; 
                                      struct _arrow_mem *ni_50;
                                      struct absolute_value_mem *ni_49;
                                      struct absolute_value_mem *ni_48;
                                      };
struct RPE_verification_5_simple_mem {struct RPE_verification_5_simple_reg {
                                      double __RPE_verification_5_simple_11;
                                      double __RPE_verification_5_simple_12;
                                      double __RPE_verification_5_simple_13;
                                      double __RPE_verification_5_simple_14;
                                      int __RPE_verification_5_simple_8;
                                      } _reg; 
                                      struct _arrow_mem *ni_47;
                                      struct min_mem *ni_46;
                                      struct absolute_value_mem *ni_45;
                                      struct absolute_value_mem *ni_44;
                                      struct absolute_value_mem *ni_43;
                                      struct absolute_value_mem *ni_42;
                                      struct absolute_value_mem *ni_41;
                                      struct absolute_value_mem *ni_40;
                                      };
struct overshoot_verification_mem {struct overshoot_verification_reg {
                                   _Bool __overshoot_verification_3;
                                   double __overshoot_verification_6;
                                   } _reg; 
                                   struct trigger_on_overshoot_mem *ni_39;
                                   struct trigger_off_overshoot_mem *ni_38;
                                   struct _arrow_mem *ni_37;
                                   struct absolute_value_mem *ni_36;
                                   };
struct rise_time_verification_mem {struct rise_time_verification_reg {
                                   double __rise_time_verification_1;
                                   int __rise_time_verification_6;
                                   _Bool __rise_time_verification_7;
                                   } _reg; 
                                   struct trigger_on_rise_time_mem *ni_35;
                                   struct trigger_off_rise_time_mem *ni_34;
                                   struct _arrow_mem *ni_33;
                                   struct absolute_value_mem *ni_32;
                                   struct eventually_3v_var_mem *ni_31;
                                   };
struct settling_time_verification_mem {struct settling_time_verification_reg {
                                       double __settling_time_verification_3;
                                       int __settling_time_verification_5;
                                       _Bool __settling_time_verification_6;
                                       } _reg; 
                                       struct trigger_on_settling_time_mem *ni_30;
                                       struct _arrow_mem *ni_29;
                                       struct absolute_value_mem *ni_28;
                                       struct always_3v_var_mem *ni_27;
                                       };
struct steady_state_verification_mem {struct _arrow_mem *ni_26;
                                      struct absolute_value_mem *ni_25;
                                      };
struct MPE_verification_5_mem {struct MPE_verification_5_reg {int __MPE_verification_5_4;
                                                              } _reg; 
                               struct _arrow_mem *ni_24;
                               struct min_mem *ni_23;
                               struct absolute_value_mem *ni_22;
                               };
struct RPE_verification_5_mem {struct RPE_verification_5_reg {int __RPE_verification_5_8;
                                                              } _reg; 
                               struct _arrow_mem *ni_21;
                               struct min_mem *ni_20;
                               struct absolute_value_mem *ni_19;
                               struct absolute_value_mem *ni_18;
                               struct absolute_value_mem *ni_17;
                               struct absolute_value_mem *ni_16;
                               struct absolute_value_mem *ni_15;
                               };
struct quadcopter_model_Lustre_STL_PP_mem {struct quadcopter_model_Lustre_STL_PP_reg {
                                           double __quadcopter_model_Lustre_STL_PP_1;
                                           double __quadcopter_model_Lustre_STL_PP_6;
                                           int __quadcopter_model_Lustre_STL_PP_8;
                                           double __quadcopter_model_Lustre_STL_PP_9;
                                           } _reg; 
                                           struct steady_state_verification_mem *ni_9;
                                           struct rise_time_verification_mem *ni_8;
                                           struct overshoot_verification_mem *ni_7;
                                           struct RPE_verification_5_simple_mem *ni_6;
                                           struct PDE_verification_5_simple_mem *ni_5;
                                           struct MPE_verification_5_simple_mem *ni_4;
                                           struct APE_verification_mem *ni_3;
                                           struct Altitudecontrol_156_003_mem *ni_2;
                                           struct absolute_value_mem *ni_14;
                                           struct _arrow_mem *ni_13;
                                           struct absolute_value_mem *ni_12;
                                           struct Attitudecontrol_496_001_mem *ni_11;
                                           struct settling_time_verification_mem *ni_10;
                                           };
struct PDE_verification_5_mem {struct PDE_verification_5_reg {int __PDE_verification_5_4;
                                                              } _reg; 
                               struct _arrow_mem *ni_1;
                               struct absolute_value_mem *ni_0;
                               };

/* Specification */

/* Node allocation function/macro prototypes */
#define min_DECLARE(attr, inst)\
  attr struct min_mem inst;\
  ;
  
#define min_LINK(inst) do {\
  ;\
} while (0)

#define min_ALLOC(attr, inst)\
  min_DECLARE(attr, inst);\
  min_LINK(inst);


#define exist_var_DECLARE(attr, inst)\
  attr struct exist_var_mem inst;\
  ;
  
#define exist_var_LINK(inst) do {\
  ;\
} while (0)

#define exist_var_ALLOC(attr, inst)\
  exist_var_DECLARE(attr, inst);\
  exist_var_LINK(inst);


#define timeab_tmp_var_DECLARE(attr, inst)\
  attr struct timeab_tmp_var_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_149);\
  min_DECLARE(attr, inst ## _ni_148);
  
#define timeab_tmp_var_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_149);\
  inst.ni_149 = &inst ## _ni_149;\
  min_LINK(inst ## _ni_148);\
  inst.ni_148 = &inst ## _ni_148;\
} while (0)

#define timeab_tmp_var_ALLOC(attr, inst)\
  timeab_tmp_var_DECLARE(attr, inst);\
  timeab_tmp_var_LINK(inst);


#define exist_DECLARE(attr, inst)\
  attr struct exist_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_147);
  
#define exist_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_147);\
  inst.ni_147 = &inst ## _ni_147;\
} while (0)

#define exist_ALLOC(attr, inst)\
  exist_DECLARE(attr, inst);\
  exist_LINK(inst);


#define kind2_times_DECLARE(attr, inst)\
  attr struct kind2_times_mem inst;\
  ;
  
#define kind2_times_LINK(inst) do {\
  ;\
} while (0)

#define kind2_times_ALLOC(attr, inst)\
  kind2_times_DECLARE(attr, inst);\
  kind2_times_LINK(inst);


#define forall_a_var_DECLARE(attr, inst)\
  attr struct forall_a_var_mem inst;\
  exist_var_DECLARE(attr, inst ## _ni_146);
  
#define forall_a_var_LINK(inst) do {\
  exist_var_LINK(inst ## _ni_146);\
  inst.ni_146 = &inst ## _ni_146;\
} while (0)

#define forall_a_var_ALLOC(attr, inst)\
  forall_a_var_DECLARE(attr, inst);\
  forall_a_var_LINK(inst);


#define timeab_var_DECLARE(attr, inst)\
  attr struct timeab_var_mem inst;\
  timeab_tmp_var_DECLARE(attr, inst ## _ni_145);
  
#define timeab_var_LINK(inst) do {\
  timeab_tmp_var_LINK(inst ## _ni_145);\
  inst.ni_145 = &inst ## _ni_145;\
} while (0)

#define timeab_var_ALLOC(attr, inst)\
  timeab_var_DECLARE(attr, inst);\
  timeab_var_LINK(inst);


#define forall_a_DECLARE(attr, inst)\
  attr struct forall_a_mem inst;\
  exist_DECLARE(attr, inst ## _ni_144);
  
#define forall_a_LINK(inst) do {\
  exist_LINK(inst ## _ni_144);\
  inst.ni_144 = &inst ## _ni_144;\
} while (0)

#define forall_a_ALLOC(attr, inst)\
  forall_a_DECLARE(attr, inst);\
  forall_a_LINK(inst);


#define Gain1_295_004_DECLARE(attr, inst)\
  attr struct Gain1_295_004_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_143);\
  kind2_times_DECLARE(attr, inst ## _ni_142);\
  kind2_times_DECLARE(attr, inst ## _ni_141);\
  kind2_times_DECLARE(attr, inst ## _ni_140);
  
#define Gain1_295_004_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_143);\
  inst.ni_143 = &inst ## _ni_143;\
  kind2_times_LINK(inst ## _ni_142);\
  inst.ni_142 = &inst ## _ni_142;\
  kind2_times_LINK(inst ## _ni_141);\
  inst.ni_141 = &inst ## _ni_141;\
  kind2_times_LINK(inst ## _ni_140);\
  inst.ni_140 = &inst ## _ni_140;\
} while (0)

#define Gain1_295_004_ALLOC(attr, inst)\
  Gain1_295_004_DECLARE(attr, inst);\
  Gain1_295_004_LINK(inst);


#define Gain2_311_001_DECLARE(attr, inst)\
  attr struct Gain2_311_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_139);\
  kind2_times_DECLARE(attr, inst ## _ni_138);\
  kind2_times_DECLARE(attr, inst ## _ni_137);\
  kind2_times_DECLARE(attr, inst ## _ni_136);
  
#define Gain2_311_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_139);\
  inst.ni_139 = &inst ## _ni_139;\
  kind2_times_LINK(inst ## _ni_138);\
  inst.ni_138 = &inst ## _ni_138;\
  kind2_times_LINK(inst ## _ni_137);\
  inst.ni_137 = &inst ## _ni_137;\
  kind2_times_LINK(inst ## _ni_136);\
  inst.ni_136 = &inst ## _ni_136;\
} while (0)

#define Gain2_311_001_ALLOC(attr, inst)\
  Gain2_311_001_DECLARE(attr, inst);\
  Gain2_311_001_LINK(inst);


#define Gain3_327_001_DECLARE(attr, inst)\
  attr struct Gain3_327_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_135);\
  kind2_times_DECLARE(attr, inst ## _ni_134);
  
#define Gain3_327_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_135);\
  inst.ni_135 = &inst ## _ni_135;\
  kind2_times_LINK(inst ## _ni_134);\
  inst.ni_134 = &inst ## _ni_134;\
} while (0)

#define Gain3_327_001_ALLOC(attr, inst)\
  Gain3_327_001_DECLARE(attr, inst);\
  Gain3_327_001_LINK(inst);


#define Gain4_343_001_DECLARE(attr, inst)\
  attr struct Gain4_343_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_133);\
  kind2_times_DECLARE(attr, inst ## _ni_132);
  
#define Gain4_343_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_133);\
  inst.ni_133 = &inst ## _ni_133;\
  kind2_times_LINK(inst ## _ni_132);\
  inst.ni_132 = &inst ## _ni_132;\
} while (0)

#define Gain4_343_001_ALLOC(attr, inst)\
  Gain4_343_001_DECLARE(attr, inst);\
  Gain4_343_001_LINK(inst);


#define Gain1_411_000_DECLARE(attr, inst)\
  attr struct Gain1_411_000_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_131);\
  kind2_times_DECLARE(attr, inst ## _ni_130);\
  kind2_times_DECLARE(attr, inst ## _ni_129);\
  kind2_times_DECLARE(attr, inst ## _ni_128);
  
#define Gain1_411_000_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_131);\
  inst.ni_131 = &inst ## _ni_131;\
  kind2_times_LINK(inst ## _ni_130);\
  inst.ni_130 = &inst ## _ni_130;\
  kind2_times_LINK(inst ## _ni_129);\
  inst.ni_129 = &inst ## _ni_129;\
  kind2_times_LINK(inst ## _ni_128);\
  inst.ni_128 = &inst ## _ni_128;\
} while (0)

#define Gain1_411_000_ALLOC(attr, inst)\
  Gain1_411_000_DECLARE(attr, inst);\
  Gain1_411_000_LINK(inst);


#define Gain2_427_001_DECLARE(attr, inst)\
  attr struct Gain2_427_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_127);\
  kind2_times_DECLARE(attr, inst ## _ni_126);
  
#define Gain2_427_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_127);\
  inst.ni_127 = &inst ## _ni_127;\
  kind2_times_LINK(inst ## _ni_126);\
  inst.ni_126 = &inst ## _ni_126;\
} while (0)

#define Gain2_427_001_ALLOC(attr, inst)\
  Gain2_427_001_DECLARE(attr, inst);\
  Gain2_427_001_LINK(inst);


#define Gain3_443_001_DECLARE(attr, inst)\
  attr struct Gain3_443_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_125);\
  kind2_times_DECLARE(attr, inst ## _ni_124);
  
#define Gain3_443_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_125);\
  inst.ni_125 = &inst ## _ni_125;\
  kind2_times_LINK(inst ## _ni_124);\
  inst.ni_124 = &inst ## _ni_124;\
} while (0)

#define Gain3_443_001_ALLOC(attr, inst)\
  Gain3_443_001_DECLARE(attr, inst);\
  Gain3_443_001_LINK(inst);


#define Gain1_513_000_DECLARE(attr, inst)\
  attr struct Gain1_513_000_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_123);\
  kind2_times_DECLARE(attr, inst ## _ni_122);\
  kind2_times_DECLARE(attr, inst ## _ni_121);\
  kind2_times_DECLARE(attr, inst ## _ni_120);
  
#define Gain1_513_000_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_123);\
  inst.ni_123 = &inst ## _ni_123;\
  kind2_times_LINK(inst ## _ni_122);\
  inst.ni_122 = &inst ## _ni_122;\
  kind2_times_LINK(inst ## _ni_121);\
  inst.ni_121 = &inst ## _ni_121;\
  kind2_times_LINK(inst ## _ni_120);\
  inst.ni_120 = &inst ## _ni_120;\
} while (0)

#define Gain1_513_000_ALLOC(attr, inst)\
  Gain1_513_000_DECLARE(attr, inst);\
  Gain1_513_000_LINK(inst);


#define Gain2_529_001_DECLARE(attr, inst)\
  attr struct Gain2_529_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_119);\
  kind2_times_DECLARE(attr, inst ## _ni_118);\
  kind2_times_DECLARE(attr, inst ## _ni_117);\
  kind2_times_DECLARE(attr, inst ## _ni_116);
  
#define Gain2_529_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_119);\
  inst.ni_119 = &inst ## _ni_119;\
  kind2_times_LINK(inst ## _ni_118);\
  inst.ni_118 = &inst ## _ni_118;\
  kind2_times_LINK(inst ## _ni_117);\
  inst.ni_117 = &inst ## _ni_117;\
  kind2_times_LINK(inst ## _ni_116);\
  inst.ni_116 = &inst ## _ni_116;\
} while (0)

#define Gain2_529_001_ALLOC(attr, inst)\
  Gain2_529_001_DECLARE(attr, inst);\
  Gain2_529_001_LINK(inst);


#define Gain3_546_001_DECLARE(attr, inst)\
  attr struct Gain3_546_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_115);\
  kind2_times_DECLARE(attr, inst ## _ni_114);
  
#define Gain3_546_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_115);\
  inst.ni_115 = &inst ## _ni_115;\
  kind2_times_LINK(inst ## _ni_114);\
  inst.ni_114 = &inst ## _ni_114;\
} while (0)

#define Gain3_546_001_ALLOC(attr, inst)\
  Gain3_546_001_DECLARE(attr, inst);\
  Gain3_546_001_LINK(inst);


#define Gain4_562_001_DECLARE(attr, inst)\
  attr struct Gain4_562_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_113);\
  kind2_times_DECLARE(attr, inst ## _ni_112);
  
#define Gain4_562_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_113);\
  inst.ni_113 = &inst ## _ni_113;\
  kind2_times_LINK(inst ## _ni_112);\
  inst.ni_112 = &inst ## _ni_112;\
} while (0)

#define Gain4_562_001_ALLOC(attr, inst)\
  Gain4_562_001_DECLARE(attr, inst);\
  Gain4_562_001_LINK(inst);


#define Gain1_707_001_DECLARE(attr, inst)\
  attr struct Gain1_707_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_111);\
  kind2_times_DECLARE(attr, inst ## _ni_110);\
  kind2_times_DECLARE(attr, inst ## _ni_109);\
  kind2_times_DECLARE(attr, inst ## _ni_108);
  
#define Gain1_707_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_111);\
  inst.ni_111 = &inst ## _ni_111;\
  kind2_times_LINK(inst ## _ni_110);\
  inst.ni_110 = &inst ## _ni_110;\
  kind2_times_LINK(inst ## _ni_109);\
  inst.ni_109 = &inst ## _ni_109;\
  kind2_times_LINK(inst ## _ni_108);\
  inst.ni_108 = &inst ## _ni_108;\
} while (0)

#define Gain1_707_001_ALLOC(attr, inst)\
  Gain1_707_001_DECLARE(attr, inst);\
  Gain1_707_001_LINK(inst);


#define Gain2_4181_001_DECLARE(attr, inst)\
  attr struct Gain2_4181_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_107);\
  kind2_times_DECLARE(attr, inst ## _ni_106);
  
#define Gain2_4181_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_107);\
  inst.ni_107 = &inst ## _ni_107;\
  kind2_times_LINK(inst ## _ni_106);\
  inst.ni_106 = &inst ## _ni_106;\
} while (0)

#define Gain2_4181_001_ALLOC(attr, inst)\
  Gain2_4181_001_DECLARE(attr, inst);\
  Gain2_4181_001_LINK(inst);


#define Gain3_4197_001_DECLARE(attr, inst)\
  attr struct Gain3_4197_001_mem inst;\
  kind2_times_DECLARE(attr, inst ## _ni_105);\
  kind2_times_DECLARE(attr, inst ## _ni_104);
  
#define Gain3_4197_001_LINK(inst) do {\
  kind2_times_LINK(inst ## _ni_105);\
  inst.ni_105 = &inst ## _ni_105;\
  kind2_times_LINK(inst ## _ni_104);\
  inst.ni_104 = &inst ## _ni_104;\
} while (0)

#define Gain3_4197_001_ALLOC(attr, inst)\
  Gain3_4197_001_DECLARE(attr, inst);\
  Gain3_4197_001_LINK(inst);


#define signal_crossing_DECLARE(attr, inst)\
  attr struct signal_crossing_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_103);
  
#define signal_crossing_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_103);\
  inst.ni_103 = &inst ## _ni_103;\
} while (0)

#define signal_crossing_ALLOC(attr, inst)\
  signal_crossing_DECLARE(attr, inst);\
  signal_crossing_LINK(inst);


#define eventually_false_var_DECLARE(attr, inst)\
  attr struct eventually_false_var_mem inst;\
  forall_a_var_DECLARE(attr, inst ## _ni_99);\
  _arrow_DECLARE(attr, inst ## _ni_102);\
  min_DECLARE(attr, inst ## _ni_101);\
  timeab_var_DECLARE(attr, inst ## _ni_100);
  
#define eventually_false_var_LINK(inst) do {\
  forall_a_var_LINK(inst ## _ni_99);\
  inst.ni_99 = &inst ## _ni_99;\
  _arrow_LINK(inst ## _ni_102);\
  inst.ni_102 = &inst ## _ni_102;\
  min_LINK(inst ## _ni_101);\
  inst.ni_101 = &inst ## _ni_101;\
  timeab_var_LINK(inst ## _ni_100);\
  inst.ni_100 = &inst ## _ni_100;\
} while (0)

#define eventually_false_var_ALLOC(attr, inst)\
  eventually_false_var_DECLARE(attr, inst);\
  eventually_false_var_LINK(inst);


#define eventually_true_var_DECLARE(attr, inst)\
  attr struct eventually_true_var_mem inst;\
  timeab_var_DECLARE(attr, inst ## _ni_98);\
  exist_var_DECLARE(attr, inst ## _ni_97);
  
#define eventually_true_var_LINK(inst) do {\
  timeab_var_LINK(inst ## _ni_98);\
  inst.ni_98 = &inst ## _ni_98;\
  exist_var_LINK(inst ## _ni_97);\
  inst.ni_97 = &inst ## _ni_97;\
} while (0)

#define eventually_true_var_ALLOC(attr, inst)\
  eventually_true_var_DECLARE(attr, inst);\
  eventually_true_var_LINK(inst);


#define absolute_value_DECLARE(attr, inst)\
  attr struct absolute_value_mem inst;\
  ;
  
#define absolute_value_LINK(inst) do {\
  ;\
} while (0)

#define absolute_value_ALLOC(attr, inst)\
  absolute_value_DECLARE(attr, inst);\
  absolute_value_LINK(inst);


#define always_false_var_DECLARE(attr, inst)\
  attr struct always_false_var_mem inst;\
  timeab_var_DECLARE(attr, inst ## _ni_96);\
  exist_DECLARE(attr, inst ## _ni_95);\
  _arrow_DECLARE(attr, inst ## _ni_94);\
  min_DECLARE(attr, inst ## _ni_93);
  
#define always_false_var_LINK(inst) do {\
  timeab_var_LINK(inst ## _ni_96);\
  inst.ni_96 = &inst ## _ni_96;\
  exist_LINK(inst ## _ni_95);\
  inst.ni_95 = &inst ## _ni_95;\
  _arrow_LINK(inst ## _ni_94);\
  inst.ni_94 = &inst ## _ni_94;\
  min_LINK(inst ## _ni_93);\
  inst.ni_93 = &inst ## _ni_93;\
} while (0)

#define always_false_var_ALLOC(attr, inst)\
  always_false_var_DECLARE(attr, inst);\
  always_false_var_LINK(inst);


#define always_true_var_DECLARE(attr, inst)\
  attr struct always_true_var_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_92);\
  min_DECLARE(attr, inst ## _ni_91);\
  timeab_var_DECLARE(attr, inst ## _ni_90);\
  forall_a_DECLARE(attr, inst ## _ni_89);
  
#define always_true_var_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_92);\
  inst.ni_92 = &inst ## _ni_92;\
  min_LINK(inst ## _ni_91);\
  inst.ni_91 = &inst ## _ni_91;\
  timeab_var_LINK(inst ## _ni_90);\
  inst.ni_90 = &inst ## _ni_90;\
  forall_a_LINK(inst ## _ni_89);\
  inst.ni_89 = &inst ## _ni_89;\
} while (0)

#define always_true_var_ALLOC(attr, inst)\
  always_true_var_DECLARE(attr, inst);\
  always_true_var_LINK(inst);


#define Controller_I_PD_161_003_DECLARE(attr, inst)\
  attr struct Controller_I_PD_161_003_mem inst;\
  Gain4_343_001_DECLARE(attr, inst ## _ni_88);\
  Gain3_327_001_DECLARE(attr, inst ## _ni_87);\
  Gain2_311_001_DECLARE(attr, inst ## _ni_86);\
  Gain1_295_004_DECLARE(attr, inst ## _ni_85);
  
#define Controller_I_PD_161_003_LINK(inst) do {\
  Gain4_343_001_LINK(inst ## _ni_88);\
  inst.ni_88 = &inst ## _ni_88;\
  Gain3_327_001_LINK(inst ## _ni_87);\
  inst.ni_87 = &inst ## _ni_87;\
  Gain2_311_001_LINK(inst ## _ni_86);\
  inst.ni_86 = &inst ## _ni_86;\
  Gain1_295_004_LINK(inst ## _ni_85);\
  inst.ni_85 = &inst ## _ni_85;\
} while (0)

#define Controller_I_PD_161_003_ALLOC(attr, inst)\
  Controller_I_PD_161_003_DECLARE(attr, inst);\
  Controller_I_PD_161_003_LINK(inst);


#define Plant_402_001_DECLARE(attr, inst)\
  attr struct Plant_402_001_mem inst;\
  Gain3_443_001_DECLARE(attr, inst ## _ni_84);\
  Gain2_427_001_DECLARE(attr, inst ## _ni_83);\
  Gain1_411_000_DECLARE(attr, inst ## _ni_82);
  
#define Plant_402_001_LINK(inst) do {\
  Gain3_443_001_LINK(inst ## _ni_84);\
  inst.ni_84 = &inst ## _ni_84;\
  Gain2_427_001_LINK(inst ## _ni_83);\
  inst.ni_83 = &inst ## _ni_83;\
  Gain1_411_000_LINK(inst ## _ni_82);\
  inst.ni_82 = &inst ## _ni_82;\
} while (0)

#define Plant_402_001_ALLOC(attr, inst)\
  Plant_402_001_DECLARE(attr, inst);\
  Plant_402_001_LINK(inst);


#define Controller_I_PD_501_000_DECLARE(attr, inst)\
  attr struct Controller_I_PD_501_000_mem inst;\
  Gain4_562_001_DECLARE(attr, inst ## _ni_81);\
  Gain3_546_001_DECLARE(attr, inst ## _ni_80);\
  Gain2_529_001_DECLARE(attr, inst ## _ni_79);\
  Gain1_513_000_DECLARE(attr, inst ## _ni_78);
  
#define Controller_I_PD_501_000_LINK(inst) do {\
  Gain4_562_001_LINK(inst ## _ni_81);\
  inst.ni_81 = &inst ## _ni_81;\
  Gain3_546_001_LINK(inst ## _ni_80);\
  inst.ni_80 = &inst ## _ni_80;\
  Gain2_529_001_LINK(inst ## _ni_79);\
  inst.ni_79 = &inst ## _ni_79;\
  Gain1_513_000_LINK(inst ## _ni_78);\
  inst.ni_78 = &inst ## _ni_78;\
} while (0)

#define Controller_I_PD_501_000_ALLOC(attr, inst)\
  Controller_I_PD_501_000_DECLARE(attr, inst);\
  Controller_I_PD_501_000_LINK(inst);


#define Plant_688_001_DECLARE(attr, inst)\
  attr struct Plant_688_001_mem inst;\
  Gain3_4197_001_DECLARE(attr, inst ## _ni_77);\
  Gain2_4181_001_DECLARE(attr, inst ## _ni_76);\
  Gain1_707_001_DECLARE(attr, inst ## _ni_75);
  
#define Plant_688_001_LINK(inst) do {\
  Gain3_4197_001_LINK(inst ## _ni_77);\
  inst.ni_77 = &inst ## _ni_77;\
  Gain2_4181_001_LINK(inst ## _ni_76);\
  inst.ni_76 = &inst ## _ni_76;\
  Gain1_707_001_LINK(inst ## _ni_75);\
  inst.ni_75 = &inst ## _ni_75;\
} while (0)

#define Plant_688_001_ALLOC(attr, inst)\
  Plant_688_001_DECLARE(attr, inst);\
  Plant_688_001_LINK(inst);


#define trigger_off_overshoot_DECLARE(attr, inst)\
  attr struct trigger_off_overshoot_mem inst;\
  signal_crossing_DECLARE(attr, inst ## _ni_74);
  
#define trigger_off_overshoot_LINK(inst) do {\
  signal_crossing_LINK(inst ## _ni_74);\
  inst.ni_74 = &inst ## _ni_74;\
} while (0)

#define trigger_off_overshoot_ALLOC(attr, inst)\
  trigger_off_overshoot_DECLARE(attr, inst);\
  trigger_off_overshoot_LINK(inst);


#define trigger_on_overshoot_DECLARE(attr, inst)\
  attr struct trigger_on_overshoot_mem inst;\
  signal_crossing_DECLARE(attr, inst ## _ni_73);
  
#define trigger_on_overshoot_LINK(inst) do {\
  signal_crossing_LINK(inst ## _ni_73);\
  inst.ni_73 = &inst ## _ni_73;\
} while (0)

#define trigger_on_overshoot_ALLOC(attr, inst)\
  trigger_on_overshoot_DECLARE(attr, inst);\
  trigger_on_overshoot_LINK(inst);


#define eventually_3v_var_DECLARE(attr, inst)\
  attr struct eventually_3v_var_mem inst;\
  eventually_true_var_DECLARE(attr, inst ## _ni_72);\
  eventually_false_var_DECLARE(attr, inst ## _ni_71);
  
#define eventually_3v_var_LINK(inst) do {\
  eventually_true_var_LINK(inst ## _ni_72);\
  inst.ni_72 = &inst ## _ni_72;\
  eventually_false_var_LINK(inst ## _ni_71);\
  inst.ni_71 = &inst ## _ni_71;\
} while (0)

#define eventually_3v_var_ALLOC(attr, inst)\
  eventually_3v_var_DECLARE(attr, inst);\
  eventually_3v_var_LINK(inst);


#define trigger_off_rise_time_DECLARE(attr, inst)\
  attr struct trigger_off_rise_time_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_70);\
  absolute_value_DECLARE(attr, inst ## _ni_69);
  
#define trigger_off_rise_time_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_70);\
  inst.ni_70 = &inst ## _ni_70;\
  absolute_value_LINK(inst ## _ni_69);\
  inst.ni_69 = &inst ## _ni_69;\
} while (0)

#define trigger_off_rise_time_ALLOC(attr, inst)\
  trigger_off_rise_time_DECLARE(attr, inst);\
  trigger_off_rise_time_LINK(inst);


#define trigger_on_rise_time_DECLARE(attr, inst)\
  attr struct trigger_on_rise_time_mem inst;\
  absolute_value_DECLARE(attr, inst ## _ni_68);\
  absolute_value_DECLARE(attr, inst ## _ni_67);\
  _arrow_DECLARE(attr, inst ## _ni_66);
  
#define trigger_on_rise_time_LINK(inst) do {\
  absolute_value_LINK(inst ## _ni_68);\
  inst.ni_68 = &inst ## _ni_68;\
  absolute_value_LINK(inst ## _ni_67);\
  inst.ni_67 = &inst ## _ni_67;\
  _arrow_LINK(inst ## _ni_66);\
  inst.ni_66 = &inst ## _ni_66;\
} while (0)

#define trigger_on_rise_time_ALLOC(attr, inst)\
  trigger_on_rise_time_DECLARE(attr, inst);\
  trigger_on_rise_time_LINK(inst);


#define always_3v_var_DECLARE(attr, inst)\
  attr struct always_3v_var_mem inst;\
  always_true_var_DECLARE(attr, inst ## _ni_65);\
  always_false_var_DECLARE(attr, inst ## _ni_64);
  
#define always_3v_var_LINK(inst) do {\
  always_true_var_LINK(inst ## _ni_65);\
  inst.ni_65 = &inst ## _ni_65;\
  always_false_var_LINK(inst ## _ni_64);\
  inst.ni_64 = &inst ## _ni_64;\
} while (0)

#define always_3v_var_ALLOC(attr, inst)\
  always_3v_var_DECLARE(attr, inst);\
  always_3v_var_LINK(inst);


#define trigger_on_settling_time_DECLARE(attr, inst)\
  attr struct trigger_on_settling_time_mem inst;\
  absolute_value_DECLARE(attr, inst ## _ni_63);\
  _arrow_DECLARE(attr, inst ## _ni_62);
  
#define trigger_on_settling_time_LINK(inst) do {\
  absolute_value_LINK(inst ## _ni_63);\
  inst.ni_63 = &inst ## _ni_63;\
  _arrow_LINK(inst ## _ni_62);\
  inst.ni_62 = &inst ## _ni_62;\
} while (0)

#define trigger_on_settling_time_ALLOC(attr, inst)\
  trigger_on_settling_time_DECLARE(attr, inst);\
  trigger_on_settling_time_LINK(inst);


#define APE_verification_DECLARE(attr, inst)\
  attr struct APE_verification_mem inst;\
  absolute_value_DECLARE(attr, inst ## _ni_61);
  
#define APE_verification_LINK(inst) do {\
  absolute_value_LINK(inst ## _ni_61);\
  inst.ni_61 = &inst ## _ni_61;\
} while (0)

#define APE_verification_ALLOC(attr, inst)\
  APE_verification_DECLARE(attr, inst);\
  APE_verification_LINK(inst);


#define Altitudecontrol_156_003_DECLARE(attr, inst)\
  attr struct Altitudecontrol_156_003_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_60);\
  Controller_I_PD_161_003_DECLARE(attr, inst ## _ni_59);\
  Plant_402_001_DECLARE(attr, inst ## _ni_58);
  
#define Altitudecontrol_156_003_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_60);\
  inst.ni_60 = &inst ## _ni_60;\
  Controller_I_PD_161_003_LINK(inst ## _ni_59);\
  inst.ni_59 = &inst ## _ni_59;\
  Plant_402_001_LINK(inst ## _ni_58);\
  inst.ni_58 = &inst ## _ni_58;\
} while (0)

#define Altitudecontrol_156_003_ALLOC(attr, inst)\
  Altitudecontrol_156_003_DECLARE(attr, inst);\
  Altitudecontrol_156_003_LINK(inst);


#define Attitudecontrol_496_001_DECLARE(attr, inst)\
  attr struct Attitudecontrol_496_001_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_57);\
  Controller_I_PD_501_000_DECLARE(attr, inst ## _ni_56);\
  Plant_688_001_DECLARE(attr, inst ## _ni_55);
  
#define Attitudecontrol_496_001_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_57);\
  inst.ni_57 = &inst ## _ni_57;\
  Controller_I_PD_501_000_LINK(inst ## _ni_56);\
  inst.ni_56 = &inst ## _ni_56;\
  Plant_688_001_LINK(inst ## _ni_55);\
  inst.ni_55 = &inst ## _ni_55;\
} while (0)

#define Attitudecontrol_496_001_ALLOC(attr, inst)\
  Attitudecontrol_496_001_DECLARE(attr, inst);\
  Attitudecontrol_496_001_LINK(inst);


#define MPE_verification_5_simple_DECLARE(attr, inst)\
  attr struct MPE_verification_5_simple_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_54);\
  min_DECLARE(attr, inst ## _ni_53);\
  absolute_value_DECLARE(attr, inst ## _ni_52);\
  absolute_value_DECLARE(attr, inst ## _ni_51);
  
#define MPE_verification_5_simple_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_54);\
  inst.ni_54 = &inst ## _ni_54;\
  min_LINK(inst ## _ni_53);\
  inst.ni_53 = &inst ## _ni_53;\
  absolute_value_LINK(inst ## _ni_52);\
  inst.ni_52 = &inst ## _ni_52;\
  absolute_value_LINK(inst ## _ni_51);\
  inst.ni_51 = &inst ## _ni_51;\
} while (0)

#define MPE_verification_5_simple_ALLOC(attr, inst)\
  MPE_verification_5_simple_DECLARE(attr, inst);\
  MPE_verification_5_simple_LINK(inst);


#define PDE_verification_5_simple_DECLARE(attr, inst)\
  attr struct PDE_verification_5_simple_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_50);\
  absolute_value_DECLARE(attr, inst ## _ni_49);\
  absolute_value_DECLARE(attr, inst ## _ni_48);
  
#define PDE_verification_5_simple_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_50);\
  inst.ni_50 = &inst ## _ni_50;\
  absolute_value_LINK(inst ## _ni_49);\
  inst.ni_49 = &inst ## _ni_49;\
  absolute_value_LINK(inst ## _ni_48);\
  inst.ni_48 = &inst ## _ni_48;\
} while (0)

#define PDE_verification_5_simple_ALLOC(attr, inst)\
  PDE_verification_5_simple_DECLARE(attr, inst);\
  PDE_verification_5_simple_LINK(inst);


#define RPE_verification_5_simple_DECLARE(attr, inst)\
  attr struct RPE_verification_5_simple_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_47);\
  min_DECLARE(attr, inst ## _ni_46);\
  absolute_value_DECLARE(attr, inst ## _ni_45);\
  absolute_value_DECLARE(attr, inst ## _ni_44);\
  absolute_value_DECLARE(attr, inst ## _ni_43);\
  absolute_value_DECLARE(attr, inst ## _ni_42);\
  absolute_value_DECLARE(attr, inst ## _ni_41);\
  absolute_value_DECLARE(attr, inst ## _ni_40);
  
#define RPE_verification_5_simple_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_47);\
  inst.ni_47 = &inst ## _ni_47;\
  min_LINK(inst ## _ni_46);\
  inst.ni_46 = &inst ## _ni_46;\
  absolute_value_LINK(inst ## _ni_45);\
  inst.ni_45 = &inst ## _ni_45;\
  absolute_value_LINK(inst ## _ni_44);\
  inst.ni_44 = &inst ## _ni_44;\
  absolute_value_LINK(inst ## _ni_43);\
  inst.ni_43 = &inst ## _ni_43;\
  absolute_value_LINK(inst ## _ni_42);\
  inst.ni_42 = &inst ## _ni_42;\
  absolute_value_LINK(inst ## _ni_41);\
  inst.ni_41 = &inst ## _ni_41;\
  absolute_value_LINK(inst ## _ni_40);\
  inst.ni_40 = &inst ## _ni_40;\
} while (0)

#define RPE_verification_5_simple_ALLOC(attr, inst)\
  RPE_verification_5_simple_DECLARE(attr, inst);\
  RPE_verification_5_simple_LINK(inst);


#define overshoot_verification_DECLARE(attr, inst)\
  attr struct overshoot_verification_mem inst;\
  trigger_on_overshoot_DECLARE(attr, inst ## _ni_39);\
  trigger_off_overshoot_DECLARE(attr, inst ## _ni_38);\
  _arrow_DECLARE(attr, inst ## _ni_37);\
  absolute_value_DECLARE(attr, inst ## _ni_36);
  
#define overshoot_verification_LINK(inst) do {\
  trigger_on_overshoot_LINK(inst ## _ni_39);\
  inst.ni_39 = &inst ## _ni_39;\
  trigger_off_overshoot_LINK(inst ## _ni_38);\
  inst.ni_38 = &inst ## _ni_38;\
  _arrow_LINK(inst ## _ni_37);\
  inst.ni_37 = &inst ## _ni_37;\
  absolute_value_LINK(inst ## _ni_36);\
  inst.ni_36 = &inst ## _ni_36;\
} while (0)

#define overshoot_verification_ALLOC(attr, inst)\
  overshoot_verification_DECLARE(attr, inst);\
  overshoot_verification_LINK(inst);


#define rise_time_verification_DECLARE(attr, inst)\
  attr struct rise_time_verification_mem inst;\
  trigger_on_rise_time_DECLARE(attr, inst ## _ni_35);\
  trigger_off_rise_time_DECLARE(attr, inst ## _ni_34);\
  _arrow_DECLARE(attr, inst ## _ni_33);\
  absolute_value_DECLARE(attr, inst ## _ni_32);\
  eventually_3v_var_DECLARE(attr, inst ## _ni_31);
  
#define rise_time_verification_LINK(inst) do {\
  trigger_on_rise_time_LINK(inst ## _ni_35);\
  inst.ni_35 = &inst ## _ni_35;\
  trigger_off_rise_time_LINK(inst ## _ni_34);\
  inst.ni_34 = &inst ## _ni_34;\
  _arrow_LINK(inst ## _ni_33);\
  inst.ni_33 = &inst ## _ni_33;\
  absolute_value_LINK(inst ## _ni_32);\
  inst.ni_32 = &inst ## _ni_32;\
  eventually_3v_var_LINK(inst ## _ni_31);\
  inst.ni_31 = &inst ## _ni_31;\
} while (0)

#define rise_time_verification_ALLOC(attr, inst)\
  rise_time_verification_DECLARE(attr, inst);\
  rise_time_verification_LINK(inst);


#define settling_time_verification_DECLARE(attr, inst)\
  attr struct settling_time_verification_mem inst;\
  trigger_on_settling_time_DECLARE(attr, inst ## _ni_30);\
  _arrow_DECLARE(attr, inst ## _ni_29);\
  absolute_value_DECLARE(attr, inst ## _ni_28);\
  always_3v_var_DECLARE(attr, inst ## _ni_27);
  
#define settling_time_verification_LINK(inst) do {\
  trigger_on_settling_time_LINK(inst ## _ni_30);\
  inst.ni_30 = &inst ## _ni_30;\
  _arrow_LINK(inst ## _ni_29);\
  inst.ni_29 = &inst ## _ni_29;\
  absolute_value_LINK(inst ## _ni_28);\
  inst.ni_28 = &inst ## _ni_28;\
  always_3v_var_LINK(inst ## _ni_27);\
  inst.ni_27 = &inst ## _ni_27;\
} while (0)

#define settling_time_verification_ALLOC(attr, inst)\
  settling_time_verification_DECLARE(attr, inst);\
  settling_time_verification_LINK(inst);


#define steady_state_verification_DECLARE(attr, inst)\
  attr struct steady_state_verification_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_26);\
  absolute_value_DECLARE(attr, inst ## _ni_25);
  
#define steady_state_verification_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_26);\
  inst.ni_26 = &inst ## _ni_26;\
  absolute_value_LINK(inst ## _ni_25);\
  inst.ni_25 = &inst ## _ni_25;\
} while (0)

#define steady_state_verification_ALLOC(attr, inst)\
  steady_state_verification_DECLARE(attr, inst);\
  steady_state_verification_LINK(inst);


#define MPE_verification_5_DECLARE(attr, inst)\
  attr struct MPE_verification_5_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_24);\
  min_DECLARE(attr, inst ## _ni_23);\
  absolute_value_DECLARE(attr, inst ## _ni_22);
  
#define MPE_verification_5_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_24);\
  inst.ni_24 = &inst ## _ni_24;\
  min_LINK(inst ## _ni_23);\
  inst.ni_23 = &inst ## _ni_23;\
  absolute_value_LINK(inst ## _ni_22);\
  inst.ni_22 = &inst ## _ni_22;\
} while (0)

#define MPE_verification_5_ALLOC(attr, inst)\
  MPE_verification_5_DECLARE(attr, inst);\
  MPE_verification_5_LINK(inst);


#define RPE_verification_5_DECLARE(attr, inst)\
  attr struct RPE_verification_5_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_21);\
  min_DECLARE(attr, inst ## _ni_20);\
  absolute_value_DECLARE(attr, inst ## _ni_19);\
  absolute_value_DECLARE(attr, inst ## _ni_18);\
  absolute_value_DECLARE(attr, inst ## _ni_17);\
  absolute_value_DECLARE(attr, inst ## _ni_16);\
  absolute_value_DECLARE(attr, inst ## _ni_15);
  
#define RPE_verification_5_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_21);\
  inst.ni_21 = &inst ## _ni_21;\
  min_LINK(inst ## _ni_20);\
  inst.ni_20 = &inst ## _ni_20;\
  absolute_value_LINK(inst ## _ni_19);\
  inst.ni_19 = &inst ## _ni_19;\
  absolute_value_LINK(inst ## _ni_18);\
  inst.ni_18 = &inst ## _ni_18;\
  absolute_value_LINK(inst ## _ni_17);\
  inst.ni_17 = &inst ## _ni_17;\
  absolute_value_LINK(inst ## _ni_16);\
  inst.ni_16 = &inst ## _ni_16;\
  absolute_value_LINK(inst ## _ni_15);\
  inst.ni_15 = &inst ## _ni_15;\
} while (0)

#define RPE_verification_5_ALLOC(attr, inst)\
  RPE_verification_5_DECLARE(attr, inst);\
  RPE_verification_5_LINK(inst);


#define quadcopter_model_Lustre_STL_PP_DECLARE(attr, inst)\
  attr struct quadcopter_model_Lustre_STL_PP_mem inst;\
  steady_state_verification_DECLARE(attr, inst ## _ni_9);\
  rise_time_verification_DECLARE(attr, inst ## _ni_8);\
  overshoot_verification_DECLARE(attr, inst ## _ni_7);\
  RPE_verification_5_simple_DECLARE(attr, inst ## _ni_6);\
  PDE_verification_5_simple_DECLARE(attr, inst ## _ni_5);\
  MPE_verification_5_simple_DECLARE(attr, inst ## _ni_4);\
  APE_verification_DECLARE(attr, inst ## _ni_3);\
  Altitudecontrol_156_003_DECLARE(attr, inst ## _ni_2);\
  absolute_value_DECLARE(attr, inst ## _ni_14);\
  _arrow_DECLARE(attr, inst ## _ni_13);\
  absolute_value_DECLARE(attr, inst ## _ni_12);\
  Attitudecontrol_496_001_DECLARE(attr, inst ## _ni_11);\
  settling_time_verification_DECLARE(attr, inst ## _ni_10);
  
#define quadcopter_model_Lustre_STL_PP_LINK(inst) do {\
  steady_state_verification_LINK(inst ## _ni_9);\
  inst.ni_9 = &inst ## _ni_9;\
  rise_time_verification_LINK(inst ## _ni_8);\
  inst.ni_8 = &inst ## _ni_8;\
  overshoot_verification_LINK(inst ## _ni_7);\
  inst.ni_7 = &inst ## _ni_7;\
  RPE_verification_5_simple_LINK(inst ## _ni_6);\
  inst.ni_6 = &inst ## _ni_6;\
  PDE_verification_5_simple_LINK(inst ## _ni_5);\
  inst.ni_5 = &inst ## _ni_5;\
  MPE_verification_5_simple_LINK(inst ## _ni_4);\
  inst.ni_4 = &inst ## _ni_4;\
  APE_verification_LINK(inst ## _ni_3);\
  inst.ni_3 = &inst ## _ni_3;\
  Altitudecontrol_156_003_LINK(inst ## _ni_2);\
  inst.ni_2 = &inst ## _ni_2;\
  absolute_value_LINK(inst ## _ni_14);\
  inst.ni_14 = &inst ## _ni_14;\
  _arrow_LINK(inst ## _ni_13);\
  inst.ni_13 = &inst ## _ni_13;\
  absolute_value_LINK(inst ## _ni_12);\
  inst.ni_12 = &inst ## _ni_12;\
  Attitudecontrol_496_001_LINK(inst ## _ni_11);\
  inst.ni_11 = &inst ## _ni_11;\
  settling_time_verification_LINK(inst ## _ni_10);\
  inst.ni_10 = &inst ## _ni_10;\
} while (0)

#define quadcopter_model_Lustre_STL_PP_ALLOC(attr, inst)\
  quadcopter_model_Lustre_STL_PP_DECLARE(attr, inst);\
  quadcopter_model_Lustre_STL_PP_LINK(inst);


#define PDE_verification_5_DECLARE(attr, inst)\
  attr struct PDE_verification_5_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_1);\
  absolute_value_DECLARE(attr, inst ## _ni_0);
  
#define PDE_verification_5_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_1);\
  inst.ni_1 = &inst ## _ni_1;\
  absolute_value_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define PDE_verification_5_ALLOC(attr, inst)\
  PDE_verification_5_DECLARE(attr, inst);\
  PDE_verification_5_LINK(inst);



#endif

