#include <assert.h>
#include "UAV_with_prop_observ.h"

/* C code generated by lustrec
   Version number 1.7
   Code is C99 compliant
   Using (double) floating-point numbers */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct min_mem {};
struct exist_var_mem {};
struct timeab_tmp_var_mem {struct timeab_tmp_var_reg {int __timeab_tmp_var_2;
                                                      } _reg; 
                           struct _arrow_mem *ni_149;
                           struct min_mem *ni_148;
                           };
struct exist_mem {struct exist_reg {_Bool __exist_2;
                                    } _reg; 
                  struct _arrow_mem *ni_147;
                  };
struct kind2_times_mem {};
struct forall_a_var_mem {struct exist_var_mem *ni_146;
                         };
struct timeab_var_mem {struct timeab_tmp_var_mem *ni_145;
                       };
struct forall_a_mem {struct exist_mem *ni_144;
                     };
struct Gain1_295_004_mem {struct kind2_times_mem *ni_143;
                          struct kind2_times_mem *ni_142;
                          struct kind2_times_mem *ni_141;
                          struct kind2_times_mem *ni_140;
                          };
struct Gain2_311_001_mem {struct kind2_times_mem *ni_139;
                          struct kind2_times_mem *ni_138;
                          struct kind2_times_mem *ni_137;
                          struct kind2_times_mem *ni_136;
                          };
struct Gain3_327_001_mem {struct kind2_times_mem *ni_135;
                          struct kind2_times_mem *ni_134;
                          };
struct Gain4_343_001_mem {struct kind2_times_mem *ni_133;
                          struct kind2_times_mem *ni_132;
                          };
struct Gain1_411_000_mem {struct kind2_times_mem *ni_131;
                          struct kind2_times_mem *ni_130;
                          struct kind2_times_mem *ni_129;
                          struct kind2_times_mem *ni_128;
                          };
struct Gain2_427_001_mem {struct kind2_times_mem *ni_127;
                          struct kind2_times_mem *ni_126;
                          };
struct Gain3_443_001_mem {struct kind2_times_mem *ni_125;
                          struct kind2_times_mem *ni_124;
                          };
struct Gain1_513_000_mem {struct kind2_times_mem *ni_123;
                          struct kind2_times_mem *ni_122;
                          struct kind2_times_mem *ni_121;
                          struct kind2_times_mem *ni_120;
                          };
struct Gain2_529_001_mem {struct kind2_times_mem *ni_119;
                          struct kind2_times_mem *ni_118;
                          struct kind2_times_mem *ni_117;
                          struct kind2_times_mem *ni_116;
                          };
struct Gain3_546_001_mem {struct kind2_times_mem *ni_115;
                          struct kind2_times_mem *ni_114;
                          };
struct Gain4_562_001_mem {struct kind2_times_mem *ni_113;
                          struct kind2_times_mem *ni_112;
                          };
struct Gain1_707_001_mem {struct kind2_times_mem *ni_111;
                          struct kind2_times_mem *ni_110;
                          struct kind2_times_mem *ni_109;
                          struct kind2_times_mem *ni_108;
                          };
struct Gain2_4181_001_mem {struct kind2_times_mem *ni_107;
                           struct kind2_times_mem *ni_106;
                           };
struct Gain3_4197_001_mem {struct kind2_times_mem *ni_105;
                           struct kind2_times_mem *ni_104;
                           };
struct signal_crossing_mem {struct signal_crossing_reg {double __signal_crossing_2;
                                                        double __signal_crossing_3;
                                                        } _reg; 
                            struct _arrow_mem *ni_103;
                            };
struct eventually_false_var_mem {struct eventually_false_var_reg {int __eventually_false_var_4;
                                                                  } _reg; 
                                 struct forall_a_var_mem *ni_99;
                                 struct _arrow_mem *ni_102;
                                 struct min_mem *ni_101;
                                 struct timeab_var_mem *ni_100;
                                 };
struct eventually_true_var_mem {struct timeab_var_mem *ni_98;
                                struct exist_var_mem *ni_97;
                                };
struct absolute_value_mem {};
struct always_false_var_mem {struct always_false_var_reg {int __always_false_var_3;
                                                          } _reg; 
                             struct timeab_var_mem *ni_96;
                             struct exist_mem *ni_95;
                             struct _arrow_mem *ni_94;
                             struct min_mem *ni_93;
                             };
struct always_true_var_mem {struct always_true_var_reg {int __always_true_var_4;
                                                        } _reg; 
                            struct _arrow_mem *ni_92;
                            struct min_mem *ni_91;
                            struct timeab_var_mem *ni_90;
                            struct forall_a_mem *ni_89;
                            };
struct Controller_I_PD_161_003_mem {struct Gain4_343_001_mem *ni_88;
                                    struct Gain3_327_001_mem *ni_87;
                                    struct Gain2_311_001_mem *ni_86;
                                    struct Gain1_295_004_mem *ni_85;
                                    };
struct Plant_402_001_mem {struct Gain3_443_001_mem *ni_84;
                          struct Gain2_427_001_mem *ni_83;
                          struct Gain1_411_000_mem *ni_82;
                          };
struct Controller_I_PD_501_000_mem {struct Gain4_562_001_mem *ni_81;
                                    struct Gain3_546_001_mem *ni_80;
                                    struct Gain2_529_001_mem *ni_79;
                                    struct Gain1_513_000_mem *ni_78;
                                    };
struct Plant_688_001_mem {struct Gain3_4197_001_mem *ni_77;
                          struct Gain2_4181_001_mem *ni_76;
                          struct Gain1_707_001_mem *ni_75;
                          };
struct trigger_off_overshoot_mem {struct signal_crossing_mem *ni_74;
                                  };
struct trigger_on_overshoot_mem {struct signal_crossing_mem *ni_73;
                                 };
struct eventually_3v_var_mem {struct eventually_true_var_mem *ni_72;
                              struct eventually_false_var_mem *ni_71;
                              };
struct trigger_off_rise_time_mem {struct trigger_off_rise_time_reg {double __trigger_off_rise_time_3;
                                                                    } _reg; 
                                  struct _arrow_mem *ni_70;
                                  struct absolute_value_mem *ni_69;
                                  };
struct trigger_on_rise_time_mem {struct trigger_on_rise_time_reg {double __trigger_on_rise_time_3;
                                                                  } _reg; 
                                 struct absolute_value_mem *ni_68;
                                 struct absolute_value_mem *ni_67;
                                 struct _arrow_mem *ni_66;
                                 };
struct always_3v_var_mem {struct always_true_var_mem *ni_65;
                          struct always_false_var_mem *ni_64;
                          };
struct trigger_on_settling_time_mem {struct trigger_on_settling_time_reg {
                                     double __trigger_on_settling_time_3;
                                     } _reg; 
                                     struct absolute_value_mem *ni_63;
                                     struct _arrow_mem *ni_62;
                                     };
struct APE_verification_mem {struct absolute_value_mem *ni_61;
                             };
struct Altitudecontrol_156_003_mem {struct Altitudecontrol_156_003_reg {
                                    double __Altitudecontrol_156_003_2;
                                    double __Altitudecontrol_156_003_3;
                                    double __Altitudecontrol_156_003_4;
                                    double __Altitudecontrol_156_003_5;
                                    double __Altitudecontrol_156_003_6;
                                    } _reg; 
                                    struct _arrow_mem *ni_60;
                                    struct Controller_I_PD_161_003_mem *ni_59;
                                    struct Plant_402_001_mem *ni_58;
                                    };
struct Attitudecontrol_496_001_mem {struct Attitudecontrol_496_001_reg {
                                    double __Attitudecontrol_496_001_2;
                                    double __Attitudecontrol_496_001_3;
                                    double __Attitudecontrol_496_001_4;
                                    double __Attitudecontrol_496_001_5;
                                    double __Attitudecontrol_496_001_6;
                                    } _reg; 
                                    struct _arrow_mem *ni_57;
                                    struct Controller_I_PD_501_000_mem *ni_56;
                                    struct Plant_688_001_mem *ni_55;
                                    };
struct MPE_verification_5_simple_mem {struct MPE_verification_5_simple_reg {
                                      double __MPE_verification_5_simple_10;
                                      int __MPE_verification_5_simple_4;
                                      double __MPE_verification_5_simple_7;
                                      double __MPE_verification_5_simple_8;
                                      double __MPE_verification_5_simple_9;
                                      } _reg; 
                                      struct _arrow_mem *ni_54;
                                      struct min_mem *ni_53;
                                      struct absolute_value_mem *ni_52;
                                      struct absolute_value_mem *ni_51;
                                      };
struct PDE_verification_5_simple_mem {struct PDE_verification_5_simple_reg {
                                      double __PDE_verification_5_simple_10;
                                      double __PDE_verification_5_simple_11;
                                      double __PDE_verification_5_simple_12;
                                      double __PDE_verification_5_simple_13;
                                      double __PDE_verification_5_simple_14;
                                      double __PDE_verification_5_simple_15;
                                      double __PDE_verification_5_simple_16;
                                      int __PDE_verification_5_simple_4;
                                      double __PDE_verification_5_simple_6;
                                      double __PDE_verification_5_simple_7;
                                      double __PDE_verification_5_simple_8;
                                      double __PDE_verification_5_simple_9;
                                      } _reg; 
                                      struct _arrow_mem *ni_50;
                                      struct absolute_value_mem *ni_49;
                                      struct absolute_value_mem *ni_48;
                                      };
struct RPE_verification_5_simple_mem {struct RPE_verification_5_simple_reg {
                                      double __RPE_verification_5_simple_11;
                                      double __RPE_verification_5_simple_12;
                                      double __RPE_verification_5_simple_13;
                                      double __RPE_verification_5_simple_14;
                                      int __RPE_verification_5_simple_8;
                                      } _reg; 
                                      struct _arrow_mem *ni_47;
                                      struct min_mem *ni_46;
                                      struct absolute_value_mem *ni_45;
                                      struct absolute_value_mem *ni_44;
                                      struct absolute_value_mem *ni_43;
                                      struct absolute_value_mem *ni_42;
                                      struct absolute_value_mem *ni_41;
                                      struct absolute_value_mem *ni_40;
                                      };
struct overshoot_verification_mem {struct overshoot_verification_reg {
                                   _Bool __overshoot_verification_3;
                                   double __overshoot_verification_6;
                                   } _reg; 
                                   struct trigger_on_overshoot_mem *ni_39;
                                   struct trigger_off_overshoot_mem *ni_38;
                                   struct _arrow_mem *ni_37;
                                   struct absolute_value_mem *ni_36;
                                   };
struct rise_time_verification_mem {struct rise_time_verification_reg {
                                   double __rise_time_verification_1;
                                   int __rise_time_verification_6;
                                   _Bool __rise_time_verification_7;
                                   } _reg; 
                                   struct trigger_on_rise_time_mem *ni_35;
                                   struct trigger_off_rise_time_mem *ni_34;
                                   struct _arrow_mem *ni_33;
                                   struct absolute_value_mem *ni_32;
                                   struct eventually_3v_var_mem *ni_31;
                                   };
struct settling_time_verification_mem {struct settling_time_verification_reg {
                                       double __settling_time_verification_3;
                                       int __settling_time_verification_5;
                                       _Bool __settling_time_verification_6;
                                       } _reg; 
                                       struct trigger_on_settling_time_mem *ni_30;
                                       struct _arrow_mem *ni_29;
                                       struct absolute_value_mem *ni_28;
                                       struct always_3v_var_mem *ni_27;
                                       };
struct steady_state_verification_mem {struct _arrow_mem *ni_26;
                                      struct absolute_value_mem *ni_25;
                                      };
struct MPE_verification_5_mem {struct MPE_verification_5_reg {int __MPE_verification_5_4;
                                                              } _reg; 
                               struct _arrow_mem *ni_24;
                               struct min_mem *ni_23;
                               struct absolute_value_mem *ni_22;
                               };
struct RPE_verification_5_mem {struct RPE_verification_5_reg {int __RPE_verification_5_8;
                                                              } _reg; 
                               struct _arrow_mem *ni_21;
                               struct min_mem *ni_20;
                               struct absolute_value_mem *ni_19;
                               struct absolute_value_mem *ni_18;
                               struct absolute_value_mem *ni_17;
                               struct absolute_value_mem *ni_16;
                               struct absolute_value_mem *ni_15;
                               };
struct quadcopter_model_Lustre_STL_PP_mem {struct quadcopter_model_Lustre_STL_PP_reg {
                                           double __quadcopter_model_Lustre_STL_PP_1;
                                           double __quadcopter_model_Lustre_STL_PP_6;
                                           int __quadcopter_model_Lustre_STL_PP_8;
                                           double __quadcopter_model_Lustre_STL_PP_9;
                                           } _reg; 
                                           struct steady_state_verification_mem *ni_9;
                                           struct rise_time_verification_mem *ni_8;
                                           struct overshoot_verification_mem *ni_7;
                                           struct RPE_verification_5_simple_mem *ni_6;
                                           struct PDE_verification_5_simple_mem *ni_5;
                                           struct MPE_verification_5_simple_mem *ni_4;
                                           struct APE_verification_mem *ni_3;
                                           struct Altitudecontrol_156_003_mem *ni_2;
                                           struct absolute_value_mem *ni_14;
                                           struct _arrow_mem *ni_13;
                                           struct absolute_value_mem *ni_12;
                                           struct Attitudecontrol_496_001_mem *ni_11;
                                           struct settling_time_verification_mem *ni_10;
                                           };
struct PDE_verification_5_mem {struct PDE_verification_5_reg {int __PDE_verification_5_4;
                                                              } _reg; 
                               struct _arrow_mem *ni_1;
                               struct absolute_value_mem *ni_0;
                               };


void min_reset (struct min_mem *self) {
  
  return;
}

void min_step (int a, int b, 
               int (*valeur_min),
               struct min_mem *self) {
  _Bool __min_1;
  
  
  __min_1 = (a <= b);
  if (__min_1) {
    *valeur_min = a;
  } else {
    *valeur_min = b;
  }
  
  return;
}

void exist_var_reset (struct exist_var_mem *self) {
  
  return;
}

void exist_var_step (_Bool inside_time_interval, _Bool prop, 
                     _Bool (*output),
                     struct exist_var_mem *self) {
  
  *output = (inside_time_interval && prop);
  return;
}

void timeab_tmp_var_reset (struct timeab_tmp_var_mem *self) {
  
  _arrow_reset(self->ni_149);
  min_reset(self->ni_148);
  return;
}

void timeab_tmp_var_step (int a, int b, 
                          int (*internal_clk), _Bool (*inside_time_interval),
                          struct timeab_tmp_var_mem *self) {
  int __timeab_tmp_var_4;
  int __timeab_tmp_var_3;
  _Bool __timeab_tmp_var_1;
  
  
  
  
  _arrow_step (1, 0, &__timeab_tmp_var_1, self->ni_149);
  if (__timeab_tmp_var_1) {
    __timeab_tmp_var_4 = 0;
  } else {
    __timeab_tmp_var_4 = (1 + self->_reg.__timeab_tmp_var_2);
  }
  min_step (__timeab_tmp_var_4, b, internal_clk, self->ni_148);
  if (__timeab_tmp_var_1) {
    __timeab_tmp_var_3 = (- 1);
  } else {
    __timeab_tmp_var_3 = self->_reg.__timeab_tmp_var_2;
  }
  *inside_time_interval = ((*internal_clk >= a) && (!(__timeab_tmp_var_3 == b)));
  self->_reg.__timeab_tmp_var_2 = *internal_clk;
  
  
  
  return;
}

void exist_reset (struct exist_mem *self) {
  
  _arrow_reset(self->ni_147);
  return;
}

void exist_step (_Bool inside_time_interval, _Bool prop, 
                 _Bool (*output),
                 struct exist_mem *self) {
  _Bool __exist_3;
  _Bool __exist_1;
  
  
  
  _arrow_step (1, 0, &__exist_1, self->ni_147);
  if (__exist_1) {
    __exist_3 = 0;
  } else {
    __exist_3 = self->_reg.__exist_2;
  }
  *output = ((inside_time_interval && prop) || __exist_3);
  self->_reg.__exist_2 = *output;
  
  
  return;
}

void kind2_times_reset (struct kind2_times_mem *self) {
  
  return;
}

void kind2_times_step (double x1, double x2, 
                       double (*prod),
                       struct kind2_times_mem *self) {
  
  *prod = (x1 * x2);
  return;
}

void forall_a_var_reset (struct forall_a_var_mem *self) {
  
  exist_var_reset(self->ni_146);
  return;
}

void forall_a_var_step (_Bool inside_time_interval, _Bool prop, 
                        _Bool (*output),
                        struct forall_a_var_mem *self) {
  _Bool __forall_a_var_1;
  
  
  exist_var_step (inside_time_interval, (!prop), &__forall_a_var_1, self->ni_146);
  *output = (!__forall_a_var_1);
  
  return;
}

void timeab_var_reset (struct timeab_var_mem *self) {
  
  timeab_tmp_var_reset(self->ni_145);
  return;
}

void timeab_var_step (int a, int b, 
                      _Bool (*inside_time_interval),
                      struct timeab_var_mem *self) {
  int iclk;
  
  
  timeab_tmp_var_step (a, b, &iclk, inside_time_interval, self->ni_145);
  
  return;
}

void forall_a_reset (struct forall_a_mem *self) {
  
  exist_reset(self->ni_144);
  return;
}

void forall_a_step (_Bool inside_time_interval, _Bool prop, 
                    _Bool (*output),
                    struct forall_a_mem *self) {
  _Bool __forall_a_1;
  
  
  exist_step (inside_time_interval, (!prop), &__forall_a_1, self->ni_144);
  *output = (!__forall_a_1);
  
  return;
}

void Gain1_295_004_reset (struct Gain1_295_004_mem *self) {
  
  kind2_times_reset(self->ni_143);
  kind2_times_reset(self->ni_142);
  kind2_times_reset(self->ni_141);
  kind2_times_reset(self->ni_140);
  return;
}

void Gain1_295_004_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain1_295_004_mem *self) {
  double __Gain1_295_004_4;
  double __Gain1_295_004_3;
  double __Gain1_295_004_2;
  double __Gain1_295_004_1;
  double Product_2;
  double Product_1;
  double K_4;
  double K_3;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  
  
  
  
  K_1 = 1.0;
  kind2_times_step (K_1, u_1, &__Gain1_295_004_4, self->ni_143);
  K_3 = 0.0;
  kind2_times_step (K_3, u_2, &__Gain1_295_004_3, self->ni_142);
  K_2 = 0.0;
  kind2_times_step (K_2, u_1, &__Gain1_295_004_2, self->ni_141);
  K_4 = 0.333333333333333;
  kind2_times_step (K_4, u_2, &__Gain1_295_004_1, self->ni_140);
  Product_2 = ((0.0 + __Gain1_295_004_2) + __Gain1_295_004_1);
  Product_1 = ((0.0 + __Gain1_295_004_4) + __Gain1_295_004_3);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  
  
  
  
  return;
}

void Gain2_311_001_reset (struct Gain2_311_001_mem *self) {
  
  kind2_times_reset(self->ni_139);
  kind2_times_reset(self->ni_138);
  kind2_times_reset(self->ni_137);
  kind2_times_reset(self->ni_136);
  return;
}

void Gain2_311_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain2_311_001_mem *self) {
  double __Gain2_311_001_4;
  double __Gain2_311_001_3;
  double __Gain2_311_001_2;
  double __Gain2_311_001_1;
  double Product_2;
  double Product_1;
  double K_4;
  double K_3;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  
  
  
  
  K_1 = 2.0;
  kind2_times_step (K_1, u_1, &__Gain2_311_001_4, self->ni_139);
  K_3 = 0.0;
  kind2_times_step (K_3, u_2, &__Gain2_311_001_3, self->ni_138);
  K_2 = 0.0;
  kind2_times_step (K_2, u_1, &__Gain2_311_001_2, self->ni_137);
  K_4 = 32.0;
  kind2_times_step (K_4, u_2, &__Gain2_311_001_1, self->ni_136);
  Product_2 = ((0.0 + __Gain2_311_001_2) + __Gain2_311_001_1);
  Product_1 = ((0.0 + __Gain2_311_001_4) + __Gain2_311_001_3);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  
  
  
  
  return;
}

void Gain3_327_001_reset (struct Gain3_327_001_mem *self) {
  
  kind2_times_reset(self->ni_135);
  kind2_times_reset(self->ni_134);
  return;
}

void Gain3_327_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1),
                         struct Gain3_327_001_mem *self) {
  double __Gain3_327_001_2;
  double __Gain3_327_001_1;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  K_1 = 1.758456850476827;
  kind2_times_step (K_1, u_1, &__Gain3_327_001_2, self->ni_135);
  K_2 = 31.944444444444446;
  kind2_times_step (K_2, u_2, &__Gain3_327_001_1, self->ni_134);
  Product_1 = ((0.0 + __Gain3_327_001_2) + __Gain3_327_001_1);
  *Out1_1 = Product_1;
  
  
  
  
  
  return;
}

void Gain4_343_001_reset (struct Gain4_343_001_mem *self) {
  
  kind2_times_reset(self->ni_133);
  kind2_times_reset(self->ni_132);
  return;
}

void Gain4_343_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1),
                         struct Gain4_343_001_mem *self) {
  double __Gain4_343_001_2;
  double __Gain4_343_001_1;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  K_1 = 1.758456850476827;
  kind2_times_step (K_1, u_1, &__Gain4_343_001_2, self->ni_133);
  K_2 = (- 1676.779424673024096);
  kind2_times_step (K_2, u_2, &__Gain4_343_001_1, self->ni_132);
  Product_1 = ((0.0 + __Gain4_343_001_2) + __Gain4_343_001_1);
  *Out1_1 = Product_1;
  
  
  
  
  
  return;
}

void Gain1_411_000_reset (struct Gain1_411_000_mem *self) {
  
  kind2_times_reset(self->ni_131);
  kind2_times_reset(self->ni_130);
  kind2_times_reset(self->ni_129);
  kind2_times_reset(self->ni_128);
  return;
}

void Gain1_411_000_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain1_411_000_mem *self) {
  double __Gain1_411_000_4;
  double __Gain1_411_000_3;
  double __Gain1_411_000_2;
  double __Gain1_411_000_1;
  double Product_2;
  double Product_1;
  double K_4;
  double K_3;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  
  
  
  
  K_1 = 1.0;
  kind2_times_step (K_1, u_1, &__Gain1_411_000_4, self->ni_131);
  K_3 = 0.0;
  kind2_times_step (K_3, u_2, &__Gain1_411_000_3, self->ni_130);
  K_2 = 0.010;
  kind2_times_step (K_2, u_1, &__Gain1_411_000_2, self->ni_129);
  K_4 = 1.0;
  kind2_times_step (K_4, u_2, &__Gain1_411_000_1, self->ni_128);
  Product_2 = ((0.0 + __Gain1_411_000_2) + __Gain1_411_000_1);
  Product_1 = ((0.0 + __Gain1_411_000_4) + __Gain1_411_000_3);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  
  
  
  
  return;
}

void Gain2_427_001_reset (struct Gain2_427_001_mem *self) {
  
  kind2_times_reset(self->ni_127);
  kind2_times_reset(self->ni_126);
  return;
}

void Gain2_427_001_step (double u_1, double __time_step, int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain2_427_001_mem *self) {
  double __Gain2_427_001_2;
  double __Gain2_427_001_1;
  double Product_2;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  K_1 = 0.010;
  kind2_times_step (K_1, u_1, &__Gain2_427_001_2, self->ni_127);
  K_2 = 0.000050;
  kind2_times_step (K_2, u_1, &__Gain2_427_001_1, self->ni_126);
  Product_2 = (0.0 + __Gain2_427_001_1);
  Product_1 = (0.0 + __Gain2_427_001_2);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  return;
}

void Gain3_443_001_reset (struct Gain3_443_001_mem *self) {
  
  kind2_times_reset(self->ni_125);
  kind2_times_reset(self->ni_124);
  return;
}

void Gain3_443_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1),
                         struct Gain3_443_001_mem *self) {
  double __Gain3_443_001_2;
  double __Gain3_443_001_1;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  K_1 = 0.0;
  kind2_times_step (K_1, u_1, &__Gain3_443_001_2, self->ni_125);
  K_2 = 1.0;
  kind2_times_step (K_2, u_2, &__Gain3_443_001_1, self->ni_124);
  Product_1 = ((0.0 + __Gain3_443_001_2) + __Gain3_443_001_1);
  *Out1_1 = Product_1;
  
  
  
  
  
  return;
}

void Gain1_513_000_reset (struct Gain1_513_000_mem *self) {
  
  kind2_times_reset(self->ni_123);
  kind2_times_reset(self->ni_122);
  kind2_times_reset(self->ni_121);
  kind2_times_reset(self->ni_120);
  return;
}

void Gain1_513_000_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain1_513_000_mem *self) {
  double __Gain1_513_000_4;
  double __Gain1_513_000_3;
  double __Gain1_513_000_2;
  double __Gain1_513_000_1;
  double Product_2;
  double Product_1;
  double K_4;
  double K_3;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  
  
  
  
  K_1 = 1.0;
  kind2_times_step (K_1, u_1, &__Gain1_513_000_4, self->ni_123);
  K_3 = 0.0;
  kind2_times_step (K_3, u_2, &__Gain1_513_000_3, self->ni_122);
  K_2 = 0.0;
  kind2_times_step (K_2, u_1, &__Gain1_513_000_2, self->ni_121);
  K_4 = 0.333333333333333;
  kind2_times_step (K_4, u_2, &__Gain1_513_000_1, self->ni_120);
  Product_2 = ((0.0 + __Gain1_513_000_2) + __Gain1_513_000_1);
  Product_1 = ((0.0 + __Gain1_513_000_4) + __Gain1_513_000_3);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  
  
  
  
  return;
}

void Gain2_529_001_reset (struct Gain2_529_001_mem *self) {
  
  kind2_times_reset(self->ni_119);
  kind2_times_reset(self->ni_118);
  kind2_times_reset(self->ni_117);
  kind2_times_reset(self->ni_116);
  return;
}

void Gain2_529_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain2_529_001_mem *self) {
  double __Gain2_529_001_4;
  double __Gain2_529_001_3;
  double __Gain2_529_001_2;
  double __Gain2_529_001_1;
  double Product_2;
  double Product_1;
  double K_4;
  double K_3;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  
  
  
  
  K_1 = 0.1250;
  kind2_times_step (K_1, u_1, &__Gain2_529_001_4, self->ni_119);
  K_3 = 0.0;
  kind2_times_step (K_3, u_2, &__Gain2_529_001_3, self->ni_118);
  K_2 = 0.0;
  kind2_times_step (K_2, u_1, &__Gain2_529_001_2, self->ni_117);
  K_4 = 2.0;
  kind2_times_step (K_4, u_2, &__Gain2_529_001_1, self->ni_116);
  Product_2 = ((0.0 + __Gain2_529_001_2) + __Gain2_529_001_1);
  Product_1 = ((0.0 + __Gain2_529_001_4) + __Gain2_529_001_3);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  
  
  
  
  return;
}

void Gain3_546_001_reset (struct Gain3_546_001_mem *self) {
  
  kind2_times_reset(self->ni_115);
  kind2_times_reset(self->ni_114);
  return;
}

void Gain3_546_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1),
                         struct Gain3_546_001_mem *self) {
  double __Gain3_546_001_2;
  double __Gain3_546_001_1;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  K_1 = 0.136456251597002;
  kind2_times_step (K_1, u_1, &__Gain3_546_001_2, self->ni_115);
  K_2 = 2.478888888888889;
  kind2_times_step (K_2, u_2, &__Gain3_546_001_1, self->ni_114);
  Product_1 = ((0.0 + __Gain3_546_001_2) + __Gain3_546_001_1);
  *Out1_1 = Product_1;
  
  
  
  
  
  return;
}

void Gain4_562_001_reset (struct Gain4_562_001_mem *self) {
  
  kind2_times_reset(self->ni_113);
  kind2_times_reset(self->ni_112);
  return;
}

void Gain4_562_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1),
                         struct Gain4_562_001_mem *self) {
  double __Gain4_562_001_2;
  double __Gain4_562_001_1;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  K_1 = 0.008528515724813;
  kind2_times_step (K_1, u_1, &__Gain4_562_001_2, self->ni_113);
  K_2 = (- 8.132380209664168);
  kind2_times_step (K_2, u_2, &__Gain4_562_001_1, self->ni_112);
  Product_1 = ((0.0 + __Gain4_562_001_2) + __Gain4_562_001_1);
  *Out1_1 = Product_1;
  
  
  
  
  
  return;
}

void Gain1_707_001_reset (struct Gain1_707_001_mem *self) {
  
  kind2_times_reset(self->ni_111);
  kind2_times_reset(self->ni_110);
  kind2_times_reset(self->ni_109);
  kind2_times_reset(self->ni_108);
  return;
}

void Gain1_707_001_step (double u_1, double u_2, double __time_step,
                         int __nb_step, 
                         double (*Out1_1), double (*Out1_2),
                         struct Gain1_707_001_mem *self) {
  double __Gain1_707_001_4;
  double __Gain1_707_001_3;
  double __Gain1_707_001_2;
  double __Gain1_707_001_1;
  double Product_2;
  double Product_1;
  double K_4;
  double K_3;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  
  
  
  
  K_1 = 1.0;
  kind2_times_step (K_1, u_1, &__Gain1_707_001_4, self->ni_111);
  K_3 = 0.0;
  kind2_times_step (K_3, u_2, &__Gain1_707_001_3, self->ni_110);
  K_2 = 0.010;
  kind2_times_step (K_2, u_1, &__Gain1_707_001_2, self->ni_109);
  K_4 = 1.0;
  kind2_times_step (K_4, u_2, &__Gain1_707_001_1, self->ni_108);
  Product_2 = ((0.0 + __Gain1_707_001_2) + __Gain1_707_001_1);
  Product_1 = ((0.0 + __Gain1_707_001_4) + __Gain1_707_001_3);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  
  
  
  
  return;
}

void Gain2_4181_001_reset (struct Gain2_4181_001_mem *self) {
  
  kind2_times_reset(self->ni_107);
  kind2_times_reset(self->ni_106);
  return;
}

void Gain2_4181_001_step (double u_1, double __time_step, int __nb_step, 
                          double (*Out1_1), double (*Out1_2),
                          struct Gain2_4181_001_mem *self) {
  double __Gain2_4181_001_2;
  double __Gain2_4181_001_1;
  double Product_2;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  
  K_1 = 2.061855670103093;
  kind2_times_step (K_1, u_1, &__Gain2_4181_001_2, self->ni_107);
  K_2 = 0.010309278350515;
  kind2_times_step (K_2, u_1, &__Gain2_4181_001_1, self->ni_106);
  Product_2 = (0.0 + __Gain2_4181_001_1);
  Product_1 = (0.0 + __Gain2_4181_001_2);
  *Out1_2 = Product_2;
  *Out1_1 = Product_1;
  
  
  
  
  
  
  return;
}

void Gain3_4197_001_reset (struct Gain3_4197_001_mem *self) {
  
  kind2_times_reset(self->ni_105);
  kind2_times_reset(self->ni_104);
  return;
}

void Gain3_4197_001_step (double u_1, double u_2, double __time_step,
                          int __nb_step, 
                          double (*Out1_1),
                          struct Gain3_4197_001_mem *self) {
  double __Gain3_4197_001_2;
  double __Gain3_4197_001_1;
  double Product_1;
  double K_2;
  double K_1;
  
  
  
  
  
  
  K_1 = 0.0;
  kind2_times_step (K_1, u_1, &__Gain3_4197_001_2, self->ni_105);
  K_2 = 1.0;
  kind2_times_step (K_2, u_2, &__Gain3_4197_001_1, self->ni_104);
  Product_1 = ((0.0 + __Gain3_4197_001_2) + __Gain3_4197_001_1);
  *Out1_1 = Product_1;
  
  
  
  
  
  return;
}

void signal_crossing_reset (struct signal_crossing_mem *self) {
  
  _arrow_reset(self->ni_103);
  return;
}

void signal_crossing_step (double ref, double sys, 
                           _Bool (*crossing),
                           struct signal_crossing_mem *self) {
  _Bool __signal_crossing_1;
  
  
  _arrow_step (1, 0, &__signal_crossing_1, self->ni_103);
  if (__signal_crossing_1) {
    *crossing = (ref == sys);
  } else {
    *crossing = (((self->_reg.__signal_crossing_3 < self->_reg.__signal_crossing_2) && (ref >= sys)) || ((self->_reg.__signal_crossing_3 > self->_reg.__signal_crossing_2) && (ref <= sys)));
  }
  self->_reg.__signal_crossing_3 = ref;
  self->_reg.__signal_crossing_2 = sys;
  
  return;
}

void eventually_false_var_reset (struct eventually_false_var_mem *self) {
  
  _arrow_reset(self->ni_102);
  min_reset(self->ni_101);
  timeab_var_reset(self->ni_100);
  forall_a_var_reset(self->ni_99);
  return;
}

void eventually_false_var_step (int a, int b, _Bool phi, 
                                _Bool (*output_ev_false),
                                struct eventually_false_var_mem *self) {
  int ev_time;
  int __eventually_false_var_5;
  _Bool __eventually_false_var_3;
  _Bool __eventually_false_var_2;
  _Bool __eventually_false_var_1;
  
  
  
  
  
  
  _arrow_step (1, 0, &__eventually_false_var_3, self->ni_102);
  if (__eventually_false_var_3) {
    __eventually_false_var_5 = 0;
  } else {
    __eventually_false_var_5 = (self->_reg.__eventually_false_var_4 + 1);
  }
  min_step (__eventually_false_var_5, b, &ev_time, self->ni_101);
  timeab_var_step (a, b, &__eventually_false_var_1, self->ni_100);
  forall_a_var_step (__eventually_false_var_1, (!phi), &__eventually_false_var_2, self->ni_99);
  *output_ev_false = ((ev_time == b) && __eventually_false_var_2);
  self->_reg.__eventually_false_var_4 = ev_time;
  
  
  
  
  
  return;
}

void eventually_true_var_reset (struct eventually_true_var_mem *self) {
  
  timeab_var_reset(self->ni_98);
  exist_var_reset(self->ni_97);
  return;
}

void eventually_true_var_step (int a, int b, _Bool phi, 
                               _Bool (*output_ev_true),
                               struct eventually_true_var_mem *self) {
  _Bool __eventually_true_var_1;
  
  
  timeab_var_step (a, b, &__eventually_true_var_1, self->ni_98);
  exist_var_step (__eventually_true_var_1, phi, output_ev_true, self->ni_97);
  
  return;
}

void absolute_value_reset (struct absolute_value_mem *self) {
  
  return;
}

void absolute_value_step (double x, 
                          double (*abs),
                          struct absolute_value_mem *self) {
  _Bool __absolute_value_1;
  
  
  __absolute_value_1 = (x >= 0.0);
  if (__absolute_value_1) {
    *abs = x;
  } else {
    *abs = (- x);
  }
  
  return;
}

void always_false_var_reset (struct always_false_var_mem *self) {
  
  timeab_var_reset(self->ni_96);
  exist_reset(self->ni_95);
  _arrow_reset(self->ni_94);
  min_reset(self->ni_93);
  return;
}

void always_false_var_step (int a, int b, _Bool phi, 
                            _Bool (*output_alw_false),
                            struct always_false_var_mem *self) {
  int alw_time;
  int __always_false_var_4;
  _Bool __always_false_var_2;
  _Bool __always_false_var_1;
  
  
  
  
  
  timeab_var_step (a, b, &__always_false_var_1, self->ni_96);
  exist_step (__always_false_var_1, (!phi), output_alw_false, self->ni_95);
  _arrow_step (1, 0, &__always_false_var_2, self->ni_94);
  if (__always_false_var_2) {
    __always_false_var_4 = 0;
  } else {
    __always_false_var_4 = (self->_reg.__always_false_var_3 + 1);
  }
  min_step (__always_false_var_4, b, &alw_time, self->ni_93);
  self->_reg.__always_false_var_3 = alw_time;
  
  
  
  
  return;
}

void always_true_var_reset (struct always_true_var_mem *self) {
  
  _arrow_reset(self->ni_92);
  min_reset(self->ni_91);
  timeab_var_reset(self->ni_90);
  forall_a_reset(self->ni_89);
  return;
}

void always_true_var_step (int a, int b, _Bool phi, 
                           _Bool (*output_alw_true),
                           struct always_true_var_mem *self) {
  int alw_time;
  int __always_true_var_5;
  _Bool __always_true_var_3;
  _Bool __always_true_var_2;
  _Bool __always_true_var_1;
  
  
  
  
  
  
  _arrow_step (1, 0, &__always_true_var_3, self->ni_92);
  if (__always_true_var_3) {
    __always_true_var_5 = 0;
  } else {
    __always_true_var_5 = (self->_reg.__always_true_var_4 + 1);
  }
  min_step (__always_true_var_5, b, &alw_time, self->ni_91);
  timeab_var_step (a, b, &__always_true_var_1, self->ni_90);
  forall_a_step (__always_true_var_1, phi, &__always_true_var_2, self->ni_89);
  *output_alw_true = ((alw_time == b) && __always_true_var_2);
  self->_reg.__always_true_var_4 = alw_time;
  
  
  
  
  
  return;
}

void Controller_I_PD_161_003_reset (struct Controller_I_PD_161_003_mem *self) {
  
  Gain4_343_001_reset(self->ni_88);
  Gain3_327_001_reset(self->ni_87);
  Gain2_311_001_reset(self->ni_86);
  Gain1_295_004_reset(self->ni_85);
  return;
}

void Controller_I_PD_161_003_step (double u_1, double xc_in_1,
                                   double xc_in_2, double yp_1,
                                   double __time_step, int __nb_step, 
                                   double (*xc_out_1), double (*xc_out_2),
                                   double (*yc_1),
                                   struct Controller_I_PD_161_003_mem *self) {
  double Vector_newline_Concatenate_2;
  double Vector_newline_Concatenate_1;
  double Sum3_1;
  double Sum2_1;
  double Sum1_2;
  double Sum1_1;
  double Gain4_1;
  double Gain3_1;
  double Gain2_2;
  double Gain2_1;
  double Gain1_2;
  double Gain1_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  Vector_newline_Concatenate_2 = yp_1;
  Sum2_1 = ((0.0 + u_1) - yp_1);
  Vector_newline_Concatenate_1 = Sum2_1;
  Gain4_343_001_step (Vector_newline_Concatenate_1, Vector_newline_Concatenate_2, __time_step, __nb_step, &Gain4_1, self->ni_88);
  Gain3_327_001_step (xc_in_1, xc_in_2, __time_step, __nb_step, &Gain3_1, self->ni_87);
  Sum3_1 = ((0.0 + Gain3_1) + Gain4_1);
  *yc_1 = Sum3_1;
  Gain2_311_001_step (Vector_newline_Concatenate_1, Vector_newline_Concatenate_2, __time_step, __nb_step, &Gain2_1, &Gain2_2, self->ni_86);
  Gain1_295_004_step (xc_in_1, xc_in_2, __time_step, __nb_step, &Gain1_1, &Gain1_2, self->ni_85);
  Sum1_2 = ((0.0 + Gain1_2) + Gain2_2);
  *xc_out_2 = Sum1_2;
  Sum1_1 = ((0.0 + Gain1_1) + Gain2_1);
  *xc_out_1 = Sum1_1;
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void Plant_402_001_reset (struct Plant_402_001_mem *self) {
  
  Gain3_443_001_reset(self->ni_84);
  Gain2_427_001_reset(self->ni_83);
  Gain1_411_000_reset(self->ni_82);
  return;
}

void Plant_402_001_step (double xp_in_1, double xp_in_2, double yc_1,
                         double __time_step, int __nb_step, 
                         double (*xp_out_1), double (*xp_out_2),
                         double (*yp_1),
                         struct Plant_402_001_mem *self) {
  double Sum1_2;
  double Sum1_1;
  double Gain3_1;
  double Gain2_2;
  double Gain2_1;
  double Gain1_2;
  double Gain1_1;
  
  
  
  
  
  
  
  
  Gain3_443_001_step (xp_in_1, xp_in_2, __time_step, __nb_step, &Gain3_1, self->ni_84);
  *yp_1 = Gain3_1;
  Gain2_427_001_step (yc_1, __time_step, __nb_step, &Gain2_1, &Gain2_2, self->ni_83);
  Gain1_411_000_step (xp_in_1, xp_in_2, __time_step, __nb_step, &Gain1_1, &Gain1_2, self->ni_82);
  Sum1_2 = ((0.0 + Gain1_2) + Gain2_2);
  *xp_out_2 = Sum1_2;
  Sum1_1 = ((0.0 + Gain1_1) + Gain2_1);
  *xp_out_1 = Sum1_1;
  
  
  
  
  
  
  
  return;
}

void Controller_I_PD_501_000_reset (struct Controller_I_PD_501_000_mem *self) {
  
  Gain4_562_001_reset(self->ni_81);
  Gain3_546_001_reset(self->ni_80);
  Gain2_529_001_reset(self->ni_79);
  Gain1_513_000_reset(self->ni_78);
  return;
}

void Controller_I_PD_501_000_step (double u_1, double xc_in_1,
                                   double xc_in_2, double yp_1,
                                   double __time_step, int __nb_step, 
                                   double (*xc_out_1), double (*xc_out_2),
                                   double (*yc_1),
                                   struct Controller_I_PD_501_000_mem *self) {
  double Vector_newline_Concatenate_2;
  double Vector_newline_Concatenate_1;
  double Sum3_1;
  double Sum2_1;
  double Sum1_2;
  double Sum1_1;
  double Gain4_1;
  double Gain3_1;
  double Gain2_2;
  double Gain2_1;
  double Gain1_2;
  double Gain1_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  Vector_newline_Concatenate_2 = yp_1;
  Sum2_1 = ((0.0 + u_1) - yp_1);
  Vector_newline_Concatenate_1 = Sum2_1;
  Gain4_562_001_step (Vector_newline_Concatenate_1, Vector_newline_Concatenate_2, __time_step, __nb_step, &Gain4_1, self->ni_81);
  Gain3_546_001_step (xc_in_1, xc_in_2, __time_step, __nb_step, &Gain3_1, self->ni_80);
  Sum3_1 = ((0.0 + Gain3_1) + Gain4_1);
  *yc_1 = Sum3_1;
  Gain2_529_001_step (Vector_newline_Concatenate_1, Vector_newline_Concatenate_2, __time_step, __nb_step, &Gain2_1, &Gain2_2, self->ni_79);
  Gain1_513_000_step (xc_in_1, xc_in_2, __time_step, __nb_step, &Gain1_1, &Gain1_2, self->ni_78);
  Sum1_2 = ((0.0 + Gain1_2) + Gain2_2);
  *xc_out_2 = Sum1_2;
  Sum1_1 = ((0.0 + Gain1_1) + Gain2_1);
  *xc_out_1 = Sum1_1;
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void Plant_688_001_reset (struct Plant_688_001_mem *self) {
  
  Gain3_4197_001_reset(self->ni_77);
  Gain2_4181_001_reset(self->ni_76);
  Gain1_707_001_reset(self->ni_75);
  return;
}

void Plant_688_001_step (double xp_in_1, double xp_in_2, double yc_1,
                         double __time_step, int __nb_step, 
                         double (*xp_out_1), double (*xp_out_2),
                         double (*yp_1),
                         struct Plant_688_001_mem *self) {
  double Sum1_2;
  double Sum1_1;
  double Gain3_1;
  double Gain2_2;
  double Gain2_1;
  double Gain1_2;
  double Gain1_1;
  
  
  
  
  
  
  
  
  Gain3_4197_001_step (xp_in_1, xp_in_2, __time_step, __nb_step, &Gain3_1, self->ni_77);
  *yp_1 = Gain3_1;
  Gain2_4181_001_step (yc_1, __time_step, __nb_step, &Gain2_1, &Gain2_2, self->ni_76);
  Gain1_707_001_step (xp_in_1, xp_in_2, __time_step, __nb_step, &Gain1_1, &Gain1_2, self->ni_75);
  Sum1_2 = ((0.0 + Gain1_2) + Gain2_2);
  *xp_out_2 = Sum1_2;
  Sum1_1 = ((0.0 + Gain1_1) + Gain2_1);
  *xp_out_1 = Sum1_1;
  
  
  
  
  
  
  
  return;
}

void trigger_off_overshoot_reset (struct trigger_off_overshoot_mem *self) {
  
  signal_crossing_reset(self->ni_74);
  return;
}

void trigger_off_overshoot_step (_Bool p_trigger, double ref, double sys, 
                                 _Bool (*trigger),
                                 struct trigger_off_overshoot_mem *self) {
  _Bool __trigger_off_overshoot_1;
  
  
  signal_crossing_step (ref, sys, &__trigger_off_overshoot_1, self->ni_74);
  *trigger = (p_trigger && __trigger_off_overshoot_1);
  
  return;
}

void trigger_on_overshoot_reset (struct trigger_on_overshoot_mem *self) {
  
  signal_crossing_reset(self->ni_73);
  return;
}

void trigger_on_overshoot_step (_Bool p_trigger, double ref, double sys, 
                                _Bool (*trigger),
                                struct trigger_on_overshoot_mem *self) {
  _Bool __trigger_on_overshoot_1;
  
  
  signal_crossing_step (ref, sys, &__trigger_on_overshoot_1, self->ni_73);
  *trigger = ((!p_trigger) && __trigger_on_overshoot_1);
  
  return;
}

void eventually_3v_var_reset (struct eventually_3v_var_mem *self) {
  
  eventually_true_var_reset(self->ni_72);
  eventually_false_var_reset(self->ni_71);
  return;
}

void eventually_3v_var_step (int a, int b, _Bool phi, 
                             _Bool (*output_ev_true),
                             _Bool (*output_ev_false),
                             struct eventually_3v_var_mem *self) {
  
  eventually_true_var_step (a, b, phi, output_ev_true, self->ni_72);
  eventually_false_var_step (a, b, phi, output_ev_false, self->ni_71);
  return;
}

void trigger_off_rise_time_reset (struct trigger_off_rise_time_mem *self) {
  
  _arrow_reset(self->ni_70);
  absolute_value_reset(self->ni_69);
  return;
}

void trigger_off_rise_time_step (_Bool p_trigger, double ref, double sys,
                                 double bound, 
                                 _Bool (*trigger),
                                 struct trigger_off_rise_time_mem *self) {
  double __trigger_off_rise_time_2;
  _Bool __trigger_off_rise_time_1;
  
  
  
  _arrow_step (1, 0, &__trigger_off_rise_time_1, self->ni_70);
  if (__trigger_off_rise_time_1) {
    *trigger = 0;
  } else {
    *trigger = (p_trigger && (self->_reg.__trigger_off_rise_time_3 < bound));
  }
  absolute_value_step ((ref - sys), &__trigger_off_rise_time_2, self->ni_69);
  self->_reg.__trigger_off_rise_time_3 = __trigger_off_rise_time_2;
  
  
  return;
}

void trigger_on_rise_time_reset (struct trigger_on_rise_time_mem *self) {
  
  absolute_value_reset(self->ni_68);
  absolute_value_reset(self->ni_67);
  _arrow_reset(self->ni_66);
  return;
}

void trigger_on_rise_time_step (_Bool p_trigger, double ref, double sys,
                                double bound, 
                                _Bool (*trigger),
                                struct trigger_on_rise_time_mem *self) {
  double __trigger_on_rise_time_4;
  double __trigger_on_rise_time_2;
  _Bool __trigger_on_rise_time_1;
  
  
  
  
  absolute_value_step ((ref - sys), &__trigger_on_rise_time_4, self->ni_68);
  absolute_value_step ((sys - ref), &__trigger_on_rise_time_2, self->ni_67);
  _arrow_step (1, 0, &__trigger_on_rise_time_1, self->ni_66);
  if (__trigger_on_rise_time_1) {
    *trigger = 0;
  } else {
    *trigger = (((!p_trigger) && (__trigger_on_rise_time_4 > bound)) && (__trigger_on_rise_time_2 <= self->_reg.__trigger_on_rise_time_3));
  }
  self->_reg.__trigger_on_rise_time_3 = __trigger_on_rise_time_2;
  
  
  
  return;
}

void always_3v_var_reset (struct always_3v_var_mem *self) {
  
  always_true_var_reset(self->ni_65);
  always_false_var_reset(self->ni_64);
  return;
}

void always_3v_var_step (int a, int b, _Bool phi, 
                         _Bool (*output_alw_true), _Bool (*output_alw_false),
                         struct always_3v_var_mem *self) {
  
  always_true_var_step (a, b, phi, output_alw_true, self->ni_65);
  always_false_var_step (a, b, phi, output_alw_false, self->ni_64);
  return;
}

void trigger_on_settling_time_reset (struct trigger_on_settling_time_mem *self) {
  
  absolute_value_reset(self->ni_63);
  _arrow_reset(self->ni_62);
  return;
}

void trigger_on_settling_time_step (_Bool p_trigger, double ref, double sys,
                                    double bound, 
                                    _Bool (*trigger),
                                    struct trigger_on_settling_time_mem *self) {
  double __trigger_on_settling_time_2;
  _Bool __trigger_on_settling_time_1;
  
  
  
  absolute_value_step ((sys - ref), &__trigger_on_settling_time_2, self->ni_63);
  _arrow_step (1, 0, &__trigger_on_settling_time_1, self->ni_62);
  if (__trigger_on_settling_time_1) {
    *trigger = 0;
  } else {
    *trigger = (((!p_trigger) && (__trigger_on_settling_time_2 > bound)) && (__trigger_on_settling_time_2 <= self->_reg.__trigger_on_settling_time_3));
  }
  self->_reg.__trigger_on_settling_time_3 = __trigger_on_settling_time_2;
  
  
  return;
}

void APE_verification_reset (struct APE_verification_mem *self) {
  
  absolute_value_reset(self->ni_61);
  return;
}

void APE_verification_step (double ref, double sys, double bound,
                            _Bool p_trigger, 
                            _Bool (*eval),
                            struct APE_verification_mem *self) {
  double __APE_verification_1;
  
  
  absolute_value_step ((sys - ref), &__APE_verification_1, self->ni_61);
  if (p_trigger) {
    *eval = (__APE_verification_1 <= bound);
  } else {
    *eval = 1;
  }
  
  return;
}

void Altitudecontrol_156_003_reset (struct Altitudecontrol_156_003_mem *self) {
  
  _arrow_reset(self->ni_60);
  Controller_I_PD_161_003_reset(self->ni_59);
  Plant_402_001_reset(self->ni_58);
  return;
}

void Altitudecontrol_156_003_step (double input_1, double __time_step,
                                   int __nb_step, 
                                   double (*yp_alt_1),
                                   struct Altitudecontrol_156_003_mem *self) {
  _Bool __Altitudecontrol_156_003_1;
  double UnitDelay_2;
  double UnitDelay_1;
  double UnitDelay2_1;
  double UnitDelay1_2;
  double UnitDelay1_1;
  double Plant_3;
  double Plant_2;
  double Plant_1;
  double Controller_I_PD_3;
  double Controller_I_PD_2;
  double Controller_I_PD_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  _arrow_step (1, 0, &__Altitudecontrol_156_003_1, self->ni_60);
  if (__Altitudecontrol_156_003_1) {
    UnitDelay_2 = 0.0;
    UnitDelay_1 = 0.0;
    UnitDelay2_1 = 0.0;
    UnitDelay1_2 = 0.0;
    UnitDelay1_1 = 0.0;
  } else {
    UnitDelay_2 = self->_reg.__Altitudecontrol_156_003_5;
    UnitDelay_1 = self->_reg.__Altitudecontrol_156_003_6;
    UnitDelay2_1 = self->_reg.__Altitudecontrol_156_003_2;
    UnitDelay1_2 = self->_reg.__Altitudecontrol_156_003_3;
    UnitDelay1_1 = self->_reg.__Altitudecontrol_156_003_4;
  }
  Controller_I_PD_161_003_step (input_1, UnitDelay_1, UnitDelay_2, UnitDelay2_1, __time_step, __nb_step, &Controller_I_PD_1, &Controller_I_PD_2, &Controller_I_PD_3, self->ni_59);
  Plant_402_001_step (UnitDelay1_1, UnitDelay1_2, Controller_I_PD_3, __time_step, __nb_step, &Plant_1, &Plant_2, &Plant_3, self->ni_58);
  *yp_alt_1 = Plant_3;
  self->_reg.__Altitudecontrol_156_003_6 = Controller_I_PD_1;
  self->_reg.__Altitudecontrol_156_003_5 = Controller_I_PD_2;
  self->_reg.__Altitudecontrol_156_003_4 = Plant_1;
  self->_reg.__Altitudecontrol_156_003_3 = Plant_2;
  self->_reg.__Altitudecontrol_156_003_2 = Plant_3;
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void Attitudecontrol_496_001_reset (struct Attitudecontrol_496_001_mem *self) {
  
  _arrow_reset(self->ni_57);
  Controller_I_PD_501_000_reset(self->ni_56);
  Plant_688_001_reset(self->ni_55);
  return;
}

void Attitudecontrol_496_001_step (double input_1, double __time_step,
                                   int __nb_step, 
                                   double (*yp_att_1),
                                   struct Attitudecontrol_496_001_mem *self) {
  _Bool __Attitudecontrol_496_001_1;
  double UnitDelay_2;
  double UnitDelay_1;
  double UnitDelay2_1;
  double UnitDelay1_2;
  double UnitDelay1_1;
  double Plant_3;
  double Plant_2;
  double Plant_1;
  double Controller_I_PD_3;
  double Controller_I_PD_2;
  double Controller_I_PD_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  _arrow_step (1, 0, &__Attitudecontrol_496_001_1, self->ni_57);
  if (__Attitudecontrol_496_001_1) {
    UnitDelay_2 = 0.0;
    UnitDelay_1 = 0.0;
    UnitDelay2_1 = 0.0;
    UnitDelay1_2 = 0.0;
    UnitDelay1_1 = 0.0;
  } else {
    UnitDelay_2 = self->_reg.__Attitudecontrol_496_001_5;
    UnitDelay_1 = self->_reg.__Attitudecontrol_496_001_6;
    UnitDelay2_1 = self->_reg.__Attitudecontrol_496_001_2;
    UnitDelay1_2 = self->_reg.__Attitudecontrol_496_001_3;
    UnitDelay1_1 = self->_reg.__Attitudecontrol_496_001_4;
  }
  Controller_I_PD_501_000_step (input_1, UnitDelay_1, UnitDelay_2, UnitDelay2_1, __time_step, __nb_step, &Controller_I_PD_1, &Controller_I_PD_2, &Controller_I_PD_3, self->ni_56);
  Plant_688_001_step (UnitDelay1_1, UnitDelay1_2, Controller_I_PD_3, __time_step, __nb_step, &Plant_1, &Plant_2, &Plant_3, self->ni_55);
  *yp_att_1 = Plant_3;
  self->_reg.__Attitudecontrol_496_001_6 = Controller_I_PD_1;
  self->_reg.__Attitudecontrol_496_001_5 = Controller_I_PD_2;
  self->_reg.__Attitudecontrol_496_001_4 = Plant_1;
  self->_reg.__Attitudecontrol_496_001_3 = Plant_2;
  self->_reg.__Attitudecontrol_496_001_2 = Plant_3;
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void MPE_verification_5_simple_reset (struct MPE_verification_5_simple_mem *self) {
  
  _arrow_reset(self->ni_54);
  min_reset(self->ni_53);
  absolute_value_reset(self->ni_52);
  absolute_value_reset(self->ni_51);
  return;
}

void MPE_verification_5_simple_step (double ref, double sys, double bound,
                                     _Bool p_trigger, 
                                     _Bool (*eval),
                                     struct MPE_verification_5_simple_mem *self) {
  double nb_samples_r;
  int nb_samples_i;
  int internal_clk;
  double e_5;
  double e_4;
  double e_3;
  double e_2;
  double e_1;
  double ave;
  int __MPE_verification_5_simple_6;
  int __MPE_verification_5_simple_5;
  _Bool __MPE_verification_5_simple_3;
  double __MPE_verification_5_simple_2;
  double __MPE_verification_5_simple_11;
  _Bool __MPE_verification_5_simple_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  nb_samples_r = 5.0;
  nb_samples_i = 5;
  _arrow_step (1, 0, &__MPE_verification_5_simple_3, self->ni_54);
  if (__MPE_verification_5_simple_3) {
    __MPE_verification_5_simple_5 = 1;
  } else {
    __MPE_verification_5_simple_5 = (self->_reg.__MPE_verification_5_simple_4 + 1);
  }
  min_step (__MPE_verification_5_simple_5, nb_samples_i, &__MPE_verification_5_simple_6, self->ni_53);
  if (p_trigger) {
    internal_clk = __MPE_verification_5_simple_6;
  } else {
    internal_clk = 1;
  }
  absolute_value_step ((ref - sys), &__MPE_verification_5_simple_11, self->ni_52);
  if (__MPE_verification_5_simple_3) {
    e_5 = 0.0;
    e_4 = 0.0;
    e_3 = 0.0;
    e_2 = 0.0;
    e_1 = 0.0;
  } else {
    e_5 = __MPE_verification_5_simple_11;
    e_4 = self->_reg.__MPE_verification_5_simple_10;
    e_3 = self->_reg.__MPE_verification_5_simple_9;
    e_2 = self->_reg.__MPE_verification_5_simple_8;
    e_1 = self->_reg.__MPE_verification_5_simple_7;
  }
  ave = (((((e_1 + e_2) + e_3) + e_4) + e_5) / nb_samples_r);
  absolute_value_step (ave, &__MPE_verification_5_simple_2, self->ni_51);
  __MPE_verification_5_simple_1 = (internal_clk == nb_samples_i);
  if (__MPE_verification_5_simple_1) {
    *eval = (__MPE_verification_5_simple_2 <= bound);
  } else {
    *eval = 1;
  }
  self->_reg.__MPE_verification_5_simple_9 = e_4;
  self->_reg.__MPE_verification_5_simple_8 = e_3;
  self->_reg.__MPE_verification_5_simple_7 = e_2;
  self->_reg.__MPE_verification_5_simple_4 = internal_clk;
  self->_reg.__MPE_verification_5_simple_10 = e_5;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void PDE_verification_5_simple_reset (struct PDE_verification_5_simple_mem *self) {
  
  _arrow_reset(self->ni_50);
  absolute_value_reset(self->ni_49);
  absolute_value_reset(self->ni_48);
  return;
}

void PDE_verification_5_simple_step (double ref, double sys, double bound,
                                     _Bool p_trigger, 
                                     _Bool (*eval),
                                     struct PDE_verification_5_simple_mem *self) {
  double nb_samples_r;
  int nb_samples_i;
  int interval;
  int internal_clk;
  double e_25;
  double e_24;
  double e_23;
  double e_22;
  double e_21;
  double e_15;
  double e_14;
  double e_13;
  double e_12;
  double e_11;
  double ave2;
  double ave1;
  _Bool __PDE_verification_5_simple_5;
  _Bool __PDE_verification_5_simple_3;
  double __PDE_verification_5_simple_2;
  double __PDE_verification_5_simple_17;
  _Bool __PDE_verification_5_simple_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  nb_samples_r = 5.0;
  nb_samples_i = 5;
  interval = 3;
  __PDE_verification_5_simple_5 = ((!p_trigger) && (self->_reg.__PDE_verification_5_simple_4 == (nb_samples_i + interval)));
  _arrow_step (1, 0, &__PDE_verification_5_simple_3, self->ni_50);
  if (__PDE_verification_5_simple_3) {
    internal_clk = 1;
  } else {
    if (__PDE_verification_5_simple_5) {
      internal_clk = 1;
    } else {
      internal_clk = (self->_reg.__PDE_verification_5_simple_4 + 1);
    }
  }
  absolute_value_step ((ref - sys), &__PDE_verification_5_simple_17, self->ni_49);
  if (__PDE_verification_5_simple_3) {
    e_25 = 0.0;
    e_24 = 0.0;
    e_23 = 0.0;
    e_22 = 0.0;
    e_21 = 0.0;
    e_15 = 0.0;
    e_14 = 0.0;
    e_13 = 0.0;
    e_12 = 0.0;
    e_11 = 0.0;
  } else {
    e_25 = __PDE_verification_5_simple_17;
    e_24 = self->_reg.__PDE_verification_5_simple_16;
    e_23 = self->_reg.__PDE_verification_5_simple_15;
    e_22 = self->_reg.__PDE_verification_5_simple_14;
    e_21 = self->_reg.__PDE_verification_5_simple_13;
    e_15 = self->_reg.__PDE_verification_5_simple_12;
    e_14 = self->_reg.__PDE_verification_5_simple_9;
    e_13 = self->_reg.__PDE_verification_5_simple_8;
    e_12 = self->_reg.__PDE_verification_5_simple_7;
    e_11 = self->_reg.__PDE_verification_5_simple_6;
  }
  ave2 = (((((e_21 + e_22) + e_23) + e_24) + e_25) / nb_samples_r);
  ave1 = (((((e_11 + e_12) + e_13) + e_14) + e_15) / nb_samples_r);
  absolute_value_step ((ave1 - ave2), &__PDE_verification_5_simple_2, self->ni_48);
  __PDE_verification_5_simple_1 = (internal_clk == (nb_samples_i + interval));
  if (__PDE_verification_5_simple_1) {
    *eval = (__PDE_verification_5_simple_2 <= bound);
  } else {
    *eval = 1;
  }
  self->_reg.__PDE_verification_5_simple_9 = e_15;
  self->_reg.__PDE_verification_5_simple_8 = e_14;
  self->_reg.__PDE_verification_5_simple_7 = e_13;
  self->_reg.__PDE_verification_5_simple_6 = e_12;
  self->_reg.__PDE_verification_5_simple_4 = internal_clk;
  self->_reg.__PDE_verification_5_simple_16 = e_25;
  self->_reg.__PDE_verification_5_simple_15 = e_24;
  self->_reg.__PDE_verification_5_simple_14 = e_23;
  self->_reg.__PDE_verification_5_simple_13 = e_22;
  self->_reg.__PDE_verification_5_simple_12 = self->_reg.__PDE_verification_5_simple_11;
  self->_reg.__PDE_verification_5_simple_11 = self->_reg.__PDE_verification_5_simple_10;
  self->_reg.__PDE_verification_5_simple_10 = e_21;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void RPE_verification_5_simple_reset (struct RPE_verification_5_simple_mem *self) {
  
  _arrow_reset(self->ni_47);
  min_reset(self->ni_46);
  absolute_value_reset(self->ni_45);
  absolute_value_reset(self->ni_44);
  absolute_value_reset(self->ni_43);
  absolute_value_reset(self->ni_42);
  absolute_value_reset(self->ni_41);
  absolute_value_reset(self->ni_40);
  return;
}

void RPE_verification_5_simple_step (double ref, double sys, double bound,
                                     _Bool p_trigger, 
                                     _Bool (*eval),
                                     struct RPE_verification_5_simple_mem *self) {
  double nb_samples_r;
  int nb_samples_i;
  int internal_clk;
  double e_5;
  double e_4;
  double e_3;
  double e_2;
  double e_1;
  double ave;
  int __RPE_verification_5_simple_9;
  _Bool __RPE_verification_5_simple_7;
  double __RPE_verification_5_simple_6;
  double __RPE_verification_5_simple_5;
  double __RPE_verification_5_simple_4;
  double __RPE_verification_5_simple_3;
  double __RPE_verification_5_simple_2;
  double __RPE_verification_5_simple_15;
  int __RPE_verification_5_simple_10;
  _Bool __RPE_verification_5_simple_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  nb_samples_r = 5.0;
  nb_samples_i = 5;
  _arrow_step (1, 0, &__RPE_verification_5_simple_7, self->ni_47);
  if (__RPE_verification_5_simple_7) {
    __RPE_verification_5_simple_9 = 1;
  } else {
    __RPE_verification_5_simple_9 = (self->_reg.__RPE_verification_5_simple_8 + 1);
  }
  min_step (__RPE_verification_5_simple_9, nb_samples_i, &__RPE_verification_5_simple_10, self->ni_46);
  if (p_trigger) {
    internal_clk = __RPE_verification_5_simple_10;
  } else {
    internal_clk = 1;
  }
  absolute_value_step ((ref - sys), &__RPE_verification_5_simple_15, self->ni_45);
  if (__RPE_verification_5_simple_7) {
    e_5 = 0.0;
    e_4 = 0.0;
    e_3 = 0.0;
    e_2 = 0.0;
    e_1 = 0.0;
  } else {
    e_5 = __RPE_verification_5_simple_15;
    e_4 = self->_reg.__RPE_verification_5_simple_14;
    e_3 = self->_reg.__RPE_verification_5_simple_13;
    e_2 = self->_reg.__RPE_verification_5_simple_12;
    e_1 = self->_reg.__RPE_verification_5_simple_11;
  }
  ave = (((((e_1 + e_2) + e_3) + e_4) + e_5) / nb_samples_r);
  absolute_value_step ((e_1 - ave), &__RPE_verification_5_simple_6, self->ni_44);
  absolute_value_step ((e_2 - ave), &__RPE_verification_5_simple_5, self->ni_43);
  absolute_value_step ((e_3 - ave), &__RPE_verification_5_simple_4, self->ni_42);
  absolute_value_step ((e_4 - ave), &__RPE_verification_5_simple_3, self->ni_41);
  absolute_value_step ((e_5 - ave), &__RPE_verification_5_simple_2, self->ni_40);
  __RPE_verification_5_simple_1 = (internal_clk == nb_samples_i);
  if (__RPE_verification_5_simple_1) {
    *eval = (((((__RPE_verification_5_simple_6 <= bound) && (__RPE_verification_5_simple_5 <= bound)) && (__RPE_verification_5_simple_4 <= bound)) && (__RPE_verification_5_simple_3 <= bound)) && (__RPE_verification_5_simple_2 <= bound));
  } else {
    *eval = 1;
  }
  self->_reg.__RPE_verification_5_simple_8 = internal_clk;
  self->_reg.__RPE_verification_5_simple_14 = e_5;
  self->_reg.__RPE_verification_5_simple_13 = e_4;
  self->_reg.__RPE_verification_5_simple_12 = e_3;
  self->_reg.__RPE_verification_5_simple_11 = e_2;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void overshoot_verification_reset (struct overshoot_verification_mem *self) {
  
  trigger_on_overshoot_reset(self->ni_39);
  trigger_off_overshoot_reset(self->ni_38);
  _arrow_reset(self->ni_37);
  absolute_value_reset(self->ni_36);
  return;
}

void overshoot_verification_step (double ref, double sys, double bound, 
                                  _Bool (*trigger), _Bool (*eval),
                                  struct overshoot_verification_mem *self) {
  _Bool __overshoot_verification_5;
  _Bool __overshoot_verification_4;
  _Bool __overshoot_verification_2;
  double __overshoot_verification_1;
  
  
  
  
  
  trigger_on_overshoot_step (self->_reg.__overshoot_verification_3, ref, sys, &__overshoot_verification_5, self->ni_39);
  trigger_off_overshoot_step (self->_reg.__overshoot_verification_3, ref, sys, &__overshoot_verification_4, self->ni_38);
  _arrow_step (1, 0, &__overshoot_verification_2, self->ni_37);
  if (__overshoot_verification_2) {
    *trigger = 0;
  } else {
    *trigger = ((self->_reg.__overshoot_verification_6 == ref) && ((__overshoot_verification_5 || self->_reg.__overshoot_verification_3) && (!__overshoot_verification_4)));
  }
  absolute_value_step ((sys - ref), &__overshoot_verification_1, self->ni_36);
  if (*trigger) {
    *eval = (__overshoot_verification_1 <= bound);
  } else {
    *eval = 1;
  }
  self->_reg.__overshoot_verification_6 = ref;
  self->_reg.__overshoot_verification_3 = *trigger;
  
  
  
  
  return;
}

void rise_time_verification_reset (struct rise_time_verification_mem *self) {
  
  trigger_on_rise_time_reset(self->ni_35);
  trigger_off_rise_time_reset(self->ni_34);
  _arrow_reset(self->ni_33);
  absolute_value_reset(self->ni_32);
  eventually_3v_var_reset(self->ni_31);
  return;
}

void rise_time_verification_step (double ref, double sys, double bound,
                                  int time_rt, int time_step, 
                                  _Bool (*trigger), _Bool (*eval),
                                  struct rise_time_verification_mem *self) {
  int time_step_reset;
  _Bool res2;
  _Bool res1;
  _Bool mres2;
  _Bool mres1;
  _Bool __rise_time_verification_9;
  _Bool __rise_time_verification_8;
  _Bool __rise_time_verification_5;
  _Bool __rise_time_verification_4;
  double __rise_time_verification_3;
  _Bool __rise_time_verification_2;
  
  
  
  
  
  
  
  
  
  
  
  
  trigger_on_rise_time_step (self->_reg.__rise_time_verification_7, ref, sys, bound, &__rise_time_verification_9, self->ni_35);
  trigger_off_rise_time_step (self->_reg.__rise_time_verification_7, ref, sys, bound, &__rise_time_verification_8, self->ni_34);
  _arrow_step (1, 0, &__rise_time_verification_4, self->ni_33);
  if (__rise_time_verification_4) {
    *trigger = 0;
  } else {
    *trigger = ((self->_reg.__rise_time_verification_1 == ref) && ((__rise_time_verification_9 || self->_reg.__rise_time_verification_7) && (!__rise_time_verification_8)));
  }
  __rise_time_verification_5 = (!(self->_reg.__rise_time_verification_1 == ref));
  if (__rise_time_verification_4) {
    time_step_reset = 0;
  } else {
    if (__rise_time_verification_5) {
      time_step_reset = time_step;
    } else {
      time_step_reset = self->_reg.__rise_time_verification_6;
    }
  }
  absolute_value_step ((sys - ref), &__rise_time_verification_3, self->ni_32);
  eventually_3v_var_step (time_step_reset, (time_rt + time_step_reset), (__rise_time_verification_3 <= bound), &mres1, &mres2, self->ni_31);
  __rise_time_verification_2 = (self->_reg.__rise_time_verification_1 == ref);
  if (__rise_time_verification_2) {
    res2 = mres2;
    res1 = mres1;
  } else {
    res2 = 0;
    res1 = 0;
  }
  if (*trigger) {
    *eval = (res1 || (!res2));
  } else {
    *eval = 1;
  }
  self->_reg.__rise_time_verification_7 = *trigger;
  self->_reg.__rise_time_verification_6 = time_step_reset;
  self->_reg.__rise_time_verification_1 = ref;
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void settling_time_verification_reset (struct settling_time_verification_mem *self) {
  
  trigger_on_settling_time_reset(self->ni_30);
  _arrow_reset(self->ni_29);
  absolute_value_reset(self->ni_28);
  always_3v_var_reset(self->ni_27);
  return;
}

void settling_time_verification_step (double ref, double sys, double bound,
                                      int time_st_observ, int time_step,
                                      int b, 
                                      _Bool (*trigger), _Bool (*eval),
                                      struct settling_time_verification_mem *self) {
  int time_step_reset;
  _Bool res2;
  _Bool res1;
  _Bool __settling_time_verification_7;
  _Bool __settling_time_verification_4;
  _Bool __settling_time_verification_2;
  double __settling_time_verification_1;
  
  
  
  
  
  
  
  
  trigger_on_settling_time_step (self->_reg.__settling_time_verification_6, ref, sys, bound, &__settling_time_verification_7, self->ni_30);
  _arrow_step (1, 0, &__settling_time_verification_2, self->ni_29);
  if (__settling_time_verification_2) {
    *trigger = 0;
  } else {
    *trigger = (((self->_reg.__settling_time_verification_3 == ref) && (__settling_time_verification_7 || self->_reg.__settling_time_verification_6)) && (!(time_step == b)));
  }
  __settling_time_verification_4 = (!(self->_reg.__settling_time_verification_3 == ref));
  if (__settling_time_verification_2) {
    time_step_reset = 0;
  } else {
    if (__settling_time_verification_4) {
      time_step_reset = time_step;
    } else {
      time_step_reset = self->_reg.__settling_time_verification_5;
    }
  }
  absolute_value_step ((sys - ref), &__settling_time_verification_1, self->ni_28);
  always_3v_var_step ((time_st_observ + time_step_reset), b, (__settling_time_verification_1 <= bound), &res1, &res2, self->ni_27);
  if (*trigger) {
    *eval = (res1 || (!res2));
  } else {
    *eval = 1;
  }
  self->_reg.__settling_time_verification_6 = *trigger;
  self->_reg.__settling_time_verification_5 = time_step_reset;
  self->_reg.__settling_time_verification_3 = ref;
  
  
  
  
  
  
  
  return;
}

void steady_state_verification_reset (struct steady_state_verification_mem *self) {
  
  _arrow_reset(self->ni_26);
  absolute_value_reset(self->ni_25);
  return;
}

void steady_state_verification_step (double ref, double sys, double bound,
                                     int time_step, int b, 
                                     _Bool (*trigger), _Bool (*eval),
                                     struct steady_state_verification_mem *self) {
  _Bool __steady_state_verification_2;
  double __steady_state_verification_1;
  
  
  
  _arrow_step (1, 0, &__steady_state_verification_2, self->ni_26);
  if (__steady_state_verification_2) {
    *trigger = 0;
  } else {
    *trigger = (time_step == b);
  }
  absolute_value_step ((sys - ref), &__steady_state_verification_1, self->ni_25);
  if (*trigger) {
    *eval = (__steady_state_verification_1 <= bound);
  } else {
    *eval = 1;
  }
  
  
  return;
}

void MPE_verification_5_reset (struct MPE_verification_5_mem *self) {
  
  _arrow_reset(self->ni_24);
  min_reset(self->ni_23);
  absolute_value_reset(self->ni_22);
  return;
}

void MPE_verification_5_step (double ref, double sys, double bound,
                              _Bool p_trigger, double e_1, double e_2,
                              double e_3, double e_4, double e_5, 
                              _Bool (*eval),
                              struct MPE_verification_5_mem *self) {
  double nb_samples_r;
  int nb_samples_i;
  int internal_clk;
  double ave;
  int __MPE_verification_5_6;
  int __MPE_verification_5_5;
  _Bool __MPE_verification_5_3;
  double __MPE_verification_5_2;
  _Bool __MPE_verification_5_1;
  
  
  
  
  
  
  
  
  
  
  nb_samples_r = 5.0;
  nb_samples_i = 5;
  _arrow_step (1, 0, &__MPE_verification_5_3, self->ni_24);
  if (__MPE_verification_5_3) {
    __MPE_verification_5_5 = 1;
  } else {
    __MPE_verification_5_5 = (self->_reg.__MPE_verification_5_4 + 1);
  }
  min_step (__MPE_verification_5_5, nb_samples_i, &__MPE_verification_5_6, self->ni_23);
  if (p_trigger) {
    internal_clk = __MPE_verification_5_6;
  } else {
    internal_clk = 1;
  }
  ave = (((((e_1 + e_2) + e_3) + e_4) + e_5) / nb_samples_r);
  absolute_value_step (ave, &__MPE_verification_5_2, self->ni_22);
  __MPE_verification_5_1 = (internal_clk == nb_samples_i);
  if (__MPE_verification_5_1) {
    *eval = (__MPE_verification_5_2 <= bound);
  } else {
    *eval = 1;
  }
  self->_reg.__MPE_verification_5_4 = internal_clk;
  
  
  
  
  
  
  
  
  
  return;
}

void RPE_verification_5_reset (struct RPE_verification_5_mem *self) {
  
  _arrow_reset(self->ni_21);
  min_reset(self->ni_20);
  absolute_value_reset(self->ni_19);
  absolute_value_reset(self->ni_18);
  absolute_value_reset(self->ni_17);
  absolute_value_reset(self->ni_16);
  absolute_value_reset(self->ni_15);
  return;
}

void RPE_verification_5_step (double ref, double sys, double bound,
                              _Bool p_trigger, double e_1, double e_2,
                              double e_3, double e_4, double e_5, 
                              _Bool (*eval),
                              struct RPE_verification_5_mem *self) {
  double nb_samples_r;
  int nb_samples_i;
  int internal_clk;
  double ave;
  int __RPE_verification_5_9;
  _Bool __RPE_verification_5_7;
  double __RPE_verification_5_6;
  double __RPE_verification_5_5;
  double __RPE_verification_5_4;
  double __RPE_verification_5_3;
  double __RPE_verification_5_2;
  int __RPE_verification_5_10;
  _Bool __RPE_verification_5_1;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  nb_samples_r = 5.0;
  nb_samples_i = 5;
  _arrow_step (1, 0, &__RPE_verification_5_7, self->ni_21);
  if (__RPE_verification_5_7) {
    __RPE_verification_5_9 = 1;
  } else {
    __RPE_verification_5_9 = (self->_reg.__RPE_verification_5_8 + 1);
  }
  min_step (__RPE_verification_5_9, nb_samples_i, &__RPE_verification_5_10, self->ni_20);
  if (p_trigger) {
    internal_clk = __RPE_verification_5_10;
  } else {
    internal_clk = 1;
  }
  ave = (((((e_1 + e_2) + e_3) + e_4) + e_5) / nb_samples_r);
  absolute_value_step ((e_1 - ave), &__RPE_verification_5_6, self->ni_19);
  absolute_value_step ((e_2 - ave), &__RPE_verification_5_5, self->ni_18);
  absolute_value_step ((e_3 - ave), &__RPE_verification_5_4, self->ni_17);
  absolute_value_step ((e_4 - ave), &__RPE_verification_5_3, self->ni_16);
  absolute_value_step ((e_5 - ave), &__RPE_verification_5_2, self->ni_15);
  __RPE_verification_5_1 = (internal_clk == nb_samples_i);
  if (__RPE_verification_5_1) {
    *eval = (((((__RPE_verification_5_6 <= bound) && (__RPE_verification_5_5 <= bound)) && (__RPE_verification_5_4 <= bound)) && (__RPE_verification_5_3 <= bound)) && (__RPE_verification_5_2 <= bound));
  } else {
    *eval = 1;
  }
  self->_reg.__RPE_verification_5_8 = internal_clk;
  
  
  
  
  
  
  
  
  
  
  
  
  
  return;
}

void quadcopter_model_Lustre_STL_PP_reset (struct quadcopter_model_Lustre_STL_PP_mem *self) {
  
  absolute_value_reset(self->ni_14);
  _arrow_reset(self->ni_13);
  absolute_value_reset(self->ni_12);
  Attitudecontrol_496_001_reset(self->ni_11);
  settling_time_verification_reset(self->ni_10);
  steady_state_verification_reset(self->ni_9);
  rise_time_verification_reset(self->ni_8);
  overshoot_verification_reset(self->ni_7);
  RPE_verification_5_simple_reset(self->ni_6);
  PDE_verification_5_simple_reset(self->ni_5);
  MPE_verification_5_simple_reset(self->ni_4);
  APE_verification_reset(self->ni_3);
  Altitudecontrol_156_003_reset(self->ni_2);
  return;
}

void quadcopter_model_Lustre_STL_PP_step (double input_att, double input_alt,
                                          double ov_spec_bound,
                                          double rt_spec_bound,
                                          double st_spec_bound,
                                          double ss_spec_bound,
                                          double APE_spec_bound,
                                          double MPE_spec_bound,
                                          double RPE_spec_bound,
                                          double PDE_spec_bound,
                                          _Bool trigger_ESA_att,
                                          int rt_spec_time, int st_spec_time,
                                          int inv_Ts, int b, 
                                          double (*__time_step),
                                          _Bool (*eval_ov_att),
                                          _Bool (*trigger_ov_att),
                                          _Bool (*eval_rt_att),
                                          _Bool (*trigger_rt_att),
                                          _Bool (*eval_st_att),
                                          _Bool (*trigger_st_att),
                                          _Bool (*eval_ss_att),
                                          _Bool (*trigger_ss_att),
                                          _Bool (*eval_APE_att),
                                          _Bool (*eval_MPE_att),
                                          _Bool (*eval_RPE_att),
                                          _Bool (*eval_PDE_att),
                                          double (*Attitudecontrol_1),
                                          struct quadcopter_model_Lustre_STL_PP_mem *self) {
  double input_change_att;
  double __quadcopter_model_Lustre_STL_PP_7;
  double __quadcopter_model_Lustre_STL_PP_5;
  _Bool __quadcopter_model_Lustre_STL_PP_4;
  double __quadcopter_model_Lustre_STL_PP_3;
  _Bool __quadcopter_model_Lustre_STL_PP_2;
  int __nb_step;
  double Altitudecontrol_1;
  
  
  
  
  
  
  
  
  
  absolute_value_step (input_att, &__quadcopter_model_Lustre_STL_PP_5, self->ni_14);
  _arrow_step (1, 0, &__quadcopter_model_Lustre_STL_PP_4, self->ni_13);
  if (__quadcopter_model_Lustre_STL_PP_4) {
    __quadcopter_model_Lustre_STL_PP_7 = __quadcopter_model_Lustre_STL_PP_5;
  } else {
    __quadcopter_model_Lustre_STL_PP_7 = self->_reg.__quadcopter_model_Lustre_STL_PP_6;
  }
  absolute_value_step ((input_att - self->_reg.__quadcopter_model_Lustre_STL_PP_1), &__quadcopter_model_Lustre_STL_PP_3, self->ni_12);
  __quadcopter_model_Lustre_STL_PP_2 = (!(self->_reg.__quadcopter_model_Lustre_STL_PP_1 == input_att));
  if (__quadcopter_model_Lustre_STL_PP_2) {
    input_change_att = __quadcopter_model_Lustre_STL_PP_3;
  } else {
    input_change_att = __quadcopter_model_Lustre_STL_PP_7;
  }
  if (__quadcopter_model_Lustre_STL_PP_4) {
    *__time_step = 0.0;
    __nb_step = 0;
  } else {
    *__time_step = (self->_reg.__quadcopter_model_Lustre_STL_PP_9 + 0.010);
    __nb_step = (self->_reg.__quadcopter_model_Lustre_STL_PP_8 + 1);
  }
  Attitudecontrol_496_001_step (input_att, *__time_step, __nb_step, Attitudecontrol_1, self->ni_11);
  settling_time_verification_step (input_att, *Attitudecontrol_1, (st_spec_bound * input_change_att), st_spec_time, __nb_step, b, trigger_st_att, eval_st_att, self->ni_10);
  steady_state_verification_step (input_att, *Attitudecontrol_1, (ss_spec_bound * input_change_att), __nb_step, b, trigger_ss_att, eval_ss_att, self->ni_9);
  rise_time_verification_step (input_att, *Attitudecontrol_1, (rt_spec_bound * input_change_att), rt_spec_time, __nb_step, trigger_rt_att, eval_rt_att, self->ni_8);
  overshoot_verification_step (input_att, *Attitudecontrol_1, (ov_spec_bound * input_change_att), trigger_ov_att, eval_ov_att, self->ni_7);
  RPE_verification_5_simple_step (input_att, *Attitudecontrol_1, (RPE_spec_bound * input_change_att), trigger_ESA_att, eval_RPE_att, self->ni_6);
  PDE_verification_5_simple_step (input_att, *Attitudecontrol_1, (PDE_spec_bound * input_change_att), trigger_ESA_att, eval_PDE_att, self->ni_5);
  MPE_verification_5_simple_step (input_att, *Attitudecontrol_1, (MPE_spec_bound * input_change_att), trigger_ESA_att, eval_MPE_att, self->ni_4);
  APE_verification_step (input_att, *Attitudecontrol_1, (APE_spec_bound * input_change_att), trigger_ESA_att, eval_APE_att, self->ni_3);
  self->_reg.__quadcopter_model_Lustre_STL_PP_9 = *__time_step;
  self->_reg.__quadcopter_model_Lustre_STL_PP_8 = __nb_step;
  self->_reg.__quadcopter_model_Lustre_STL_PP_6 = input_change_att;
  self->_reg.__quadcopter_model_Lustre_STL_PP_1 = input_att;
  Altitudecontrol_156_003_step (input_alt, *__time_step, __nb_step, &Altitudecontrol_1, self->ni_2);
  
  
  
  
  
  
  
  
  return;
}

void PDE_verification_5_reset (struct PDE_verification_5_mem *self) {
  
  _arrow_reset(self->ni_1);
  absolute_value_reset(self->ni_0);
  return;
}

void PDE_verification_5_step (double ref, double sys, double bound,
                              _Bool p_trigger, int interval, double e_11,
                              double e_12, double e_13, double e_14,
                              double e_15, double e_21, double e_22,
                              double e_23, double e_24, double e_25, 
                              _Bool (*eval),
                              struct PDE_verification_5_mem *self) {
  double nb_samples_r;
  int nb_samples_i;
  int internal_clk;
  double ave2;
  double ave1;
  _Bool __PDE_verification_5_5;
  _Bool __PDE_verification_5_3;
  double __PDE_verification_5_2;
  _Bool __PDE_verification_5_1;
  
  
  
  
  
  
  
  
  
  
  nb_samples_r = 5.0;
  nb_samples_i = 5;
  __PDE_verification_5_5 = ((!p_trigger) && (self->_reg.__PDE_verification_5_4 == (nb_samples_i + interval)));
  _arrow_step (1, 0, &__PDE_verification_5_3, self->ni_1);
  if (__PDE_verification_5_3) {
    internal_clk = 1;
  } else {
    if (__PDE_verification_5_5) {
      internal_clk = 1;
    } else {
      internal_clk = (self->_reg.__PDE_verification_5_4 + 1);
    }
  }
  ave2 = (((((e_21 + e_22) + e_23) + e_24) + e_25) / nb_samples_r);
  ave1 = (((((e_11 + e_12) + e_13) + e_14) + e_15) / nb_samples_r);
  absolute_value_step ((ave1 - ave2), &__PDE_verification_5_2, self->ni_0);
  __PDE_verification_5_1 = (internal_clk == (nb_samples_i + interval));
  if (__PDE_verification_5_1) {
    *eval = (__PDE_verification_5_2 <= bound);
  } else {
    *eval = 1;
  }
  self->_reg.__PDE_verification_5_4 = internal_clk;
  
  
  
  
  
  
  
  
  
  return;
}

